"""HTTPS, certificate and transport-security tests.

These use a real certificate generated by the project's own tooling, a real
uvicorn TLS listener, and a real client that **verifies** the certificate
against the CA. Nothing here sets verify=False.
"""

import socket
import ssl
import threading
import time

import httpx
import pytest
import uvicorn

from agent.main import TLSConfigError, create_app, create_redirect_app, main, resolve_tls
from agent.security.auth import hash_password
from agent.security.certs import create_ca, issue_server_certificate, provision
from agent.tailscale import tailscale_status
from agent.security.tls import inspect_certificate, verify_endpoint

PASSWORD = "correct horse battery"


def free_port() -> int:
    with socket.socket() as sock:
        sock.bind(("127.0.0.1", 0))
        return sock.getsockname()[1]


@pytest.fixture
def tls_config(config, monkeypatch):
    """A config with a real CA-signed certificate for 127.0.0.1/localhost."""
    monkeypatch.setenv("MCSC_ADMIN_USERNAME", "admin")
    monkeypatch.setenv("MCSC_ADMIN_PASSWORD_HASH", hash_password(PASSWORD, rounds=1000))
    monkeypatch.delenv("MCSC_API_TOKEN", raising=False)
    cert_dir = config.cert_dir
    result = issue_server_certificate(cert_dir, ["localhost", "minecraft-pc.tailnet.ts.net"],
                                      ["127.0.0.1"])
    config.set("tls.enabled", True)
    config.set("tls.certificate", result["cert_path"])
    config.set("tls.private_key", result["key_path"])
    config.set("tls.ca_certificate", result["ca_path"])
    config.set("tls.hostname", "localhost")
    config.set("network.host", "127.0.0.1")
    config.set("network.port", free_port())
    return config


# ---------------------------------------------------------------- generation
def test_generated_certificate_has_the_right_names(config):
    result = issue_server_certificate(config.cert_dir,
                                      ["minecraft-pc.tailnet.ts.net", "localhost"],
                                      ["100.101.102.103", "127.0.0.1"])
    info = inspect_certificate(result["cert_path"], result["key_path"])
    assert info.parsed is True
    assert info.covers("minecraft-pc.tailnet.ts.net") is True
    assert info.covers("100.101.102.103") is True
    assert info.covers("evil.example.com") is False
    assert info.key_matches_certificate is True
    assert info.self_signed is False, "the leaf must be signed by the CA, not by itself"


def test_certificate_lifetime_is_browser_acceptable(config):
    result = issue_server_certificate(config.cert_dir, ["localhost"], ["127.0.0.1"])
    info = inspect_certificate(result["cert_path"])
    assert 390 < info.days_remaining <= 398, "browsers reject leaf certificates over 398 days"


def test_reissuing_keeps_the_same_ca(config):
    """Renewal must not force you to re-trust the CA on every device."""
    issue_server_certificate(config.cert_dir, ["localhost"], ["127.0.0.1"])
    ca_bytes = (config.cert_dir / "ca.crt").read_bytes()
    second = issue_server_certificate(config.cert_dir, ["localhost"], ["127.0.0.1"])
    assert (config.cert_dir / "ca.crt").read_bytes() == ca_bytes
    assert inspect_certificate(second["cert_path"], second["key_path"]).key_matches_certificate


def test_mismatched_key_is_detected(config):
    good = issue_server_certificate(config.cert_dir, ["localhost"], ["127.0.0.1"])
    other_dir = config.cert_dir.parent / "other"
    create_ca(other_dir)
    other = issue_server_certificate(other_dir, ["localhost"], ["127.0.0.1"])
    info = inspect_certificate(good["cert_path"], other["key_path"])
    assert info.key_matches_certificate is False


def test_expiry_severity_tiers(config):
    result = issue_server_certificate(config.cert_dir, ["localhost"], ["127.0.0.1"])
    now = time.time()
    assert inspect_certificate(result["cert_path"], now=now).expiry_severity == "ok"
    soon = now + (398 - 10) * 86400
    assert inspect_certificate(result["cert_path"], now=soon).expiry_severity == "warn"
    sooner = now + (398 - 2) * 86400
    assert inspect_certificate(result["cert_path"], now=sooner).expiry_severity == "critical"
    past = now + 400 * 86400
    info = inspect_certificate(result["cert_path"], now=past)
    assert info.expired is True
    assert info.expiry_severity == "critical"


def test_unreadable_certificate_reports_unknown_not_valid(config):
    bad = config.cert_dir
    bad.mkdir(parents=True, exist_ok=True)
    path = bad / "broken.crt"
    path.write_text("this is not a certificate")
    info = inspect_certificate(path)
    assert info.parsed is False
    assert info.days_remaining is None
    assert info.expiry_severity == "unknown"
    assert info.covers("localhost") is None


def test_missing_certificate_reports_absent(config):
    info = inspect_certificate(config.cert_dir / "nope.crt")
    assert info.certificate_present is False
    assert info.parsed is False


def test_certificate_info_never_carries_key_material(config):
    result = issue_server_certificate(config.cert_dir, ["localhost"], ["127.0.0.1"])
    info = inspect_certificate(result["cert_path"], result["key_path"])
    blob = repr(info.to_dict())
    assert "PRIVATE KEY" not in blob
    assert "BEGIN" not in blob


def test_tailscale_status_is_unknown_when_cli_is_absent(monkeypatch):
    monkeypatch.setattr("agent.tailscale.tailscale_binary", lambda: None)
    status = tailscale_status()
    assert status["cli_found"] is False
    assert status["connected"] is None, "absence of the CLI must not read as 'not connected'"
    assert status["error"]


def test_provision_falls_back_to_local_ca_without_tailscale(config, monkeypatch):
    monkeypatch.setattr("agent.tailscale.tailscale_binary", lambda: None)
    report = provision(config.cert_dir)
    assert report["result"]["strategy"] == "local_ca"
    assert report["tailscale"]["cli_found"] is False


# ---------------------------------------------------------------- startup gate
def test_agent_refuses_to_start_https_without_a_certificate(config):
    config.set("tls.enabled", True)
    config.set("tls.certificate", str(config.cert_dir / "missing.crt"))
    config.set("tls.private_key", str(config.cert_dir / "missing.key"))
    with pytest.raises(TLSConfigError, match="not found"):
        resolve_tls(config)


def test_agent_refuses_a_mismatched_key_at_startup(config):
    good = issue_server_certificate(config.cert_dir, ["localhost"], ["127.0.0.1"])
    other_dir = config.cert_dir.parent / "other"
    other = issue_server_certificate(other_dir, ["localhost"], ["127.0.0.1"])
    config.set("tls.enabled", True)
    config.set("tls.certificate", good["cert_path"])
    config.set("tls.private_key", other["key_path"])
    with pytest.raises(TLSConfigError, match="does not match"):
        resolve_tls(config)


def test_plain_http_is_refused_on_a_non_loopback_address(config, capsys, monkeypatch, tmp_path):
    """HTTP must never carry credentials across a network."""
    cfg_file = tmp_path / "config.yaml"
    config.set("tls.enabled", False)
    config.set("network.host", "100.101.102.103")
    config.save(cfg_file)
    monkeypatch.setenv("MCSC_ADMIN_PASSWORD_HASH", hash_password(PASSWORD, rounds=1000))
    code = main(["--config", str(cfg_file), "--no-tls"])
    assert code == 2
    assert "Refusing to serve plain HTTP" in capsys.readouterr().err


# ---------------------------------------------------------------- live server
class TLSServer:
    def __init__(self, config):
        self.config = config
        certfile, keyfile = resolve_tls(config)
        self.port = int(config.get("network.port"))
        uvicorn_config = uvicorn.Config(
            create_app(config), host="127.0.0.1", port=self.port,
            ssl_certfile=certfile, ssl_keyfile=keyfile,
            log_level="warning", access_log=False,
        )
        self.server = uvicorn.Server(uvicorn_config)
        self.thread = threading.Thread(target=self.server.run, daemon=True)

    def __enter__(self):
        self.thread.start()
        deadline = time.time() + 20
        while time.time() < deadline and not self.server.started:
            time.sleep(0.05)
        if not self.server.started:
            raise RuntimeError("the TLS server did not start")
        return self

    def __exit__(self, *exc):
        self.server.should_exit = True
        self.thread.join(timeout=20)


@pytest.fixture
def live_tls(tls_config):
    with TLSServer(tls_config) as server:
        yield tls_config, server.port


def test_https_serves_the_dashboard_with_certificate_verification(live_tls):
    config, port = live_tls
    # verify against the CA bundle; verification is never switched off
    with httpx.Client(verify=str(config.tls_ca_certificate)) as client:
        response = client.get(f"https://localhost:{port}/api/health")
        assert response.status_code == 200
        assert response.json()["ok"] is True
        page = client.get(f"https://localhost:{port}/")
        assert page.status_code == 200
        assert "Minecraft Server Control" in page.text


def test_untrusted_client_rejects_the_private_ca(live_tls):
    """Proof the certificate is actually being checked: without the CA the
    connection must fail, not succeed."""
    config, port = live_tls
    with httpx.Client() as client:  # system trust store only
        with pytest.raises(httpx.ConnectError):
            client.get(f"https://localhost:{port}/api/health")


def test_tls_handshake_self_check_verifies(live_tls):
    config, port = live_tls
    result = verify_endpoint("127.0.0.1", port, config.tls_ca_certificate,
                             server_hostname="localhost")
    assert result["verified"] is True
    assert result["protocol"].startswith("TLSv1.")


def test_tls_self_check_reports_a_hostname_mismatch_honestly(live_tls):
    config, port = live_tls
    result = verify_endpoint("127.0.0.1", port, config.tls_ca_certificate,
                             server_hostname="not-in-the-certificate.example")
    assert result["verified"] is False
    assert "not trusted" in result["error"] or "match" in result["error"].lower()


def test_hsts_is_sent_over_https_but_not_on_loopback(live_tls):
    """HSTS on 127.0.0.1 would poison local development permanently."""
    config, port = live_tls
    with httpx.Client(verify=str(config.tls_ca_certificate)) as client:
        loopback = client.get(f"https://localhost:{port}/api/health")
        assert "Strict-Transport-Security" not in loopback.headers
        named = client.get(f"https://localhost:{port}/api/health",
                           headers={"Host": "minecraft-pc.tailnet.ts.net"})
        assert "Strict-Transport-Security" in named.headers
        assert "max-age=" in named.headers["Strict-Transport-Security"]


def test_security_headers_over_https(live_tls):
    config, port = live_tls
    with httpx.Client(verify=str(config.tls_ca_certificate)) as client:
        headers = client.get(f"https://localhost:{port}/api/health").headers
    assert headers["X-Frame-Options"] == "DENY"
    assert headers["X-Content-Type-Options"] == "nosniff"
    assert headers["Referrer-Policy"] == "no-referrer"
    csp = headers["Content-Security-Policy"]
    assert "script-src 'self'" in csp
    assert "script-src *" not in csp
    assert "'unsafe-eval'" not in csp
    assert "frame-ancestors 'none'" in csp


def test_authentication_still_enforced_over_https(live_tls):
    config, port = live_tls
    base = f"https://localhost:{port}"
    with httpx.Client(verify=str(config.tls_ca_certificate)) as client:
        assert client.get(f"{base}/api/status").status_code == 401
        token = client.post(f"{base}/api/auth/login",
                            json={"username": "admin", "password": PASSWORD}).json()["token"]
        auth = {"Authorization": f"Bearer {token}"}
        assert client.get(f"{base}/api/status", headers=auth).status_code == 200
        # dangerous command still needs confirmation, over HTTPS too
        refused = client.post(f"{base}/api/server/command", headers=auth,
                              json={"command": "stop"})
        assert refused.status_code == 400
        assert "confirmation" in refused.json()["detail"]


def test_wss_streams_events_after_authentication(live_tls):
    """A real wss:// connection, verified against the CA, carrying live events."""
    config, port = live_tls
    import json

    with httpx.Client(verify=str(config.tls_ca_certificate)) as client:
        token = client.post(f"https://localhost:{port}/api/auth/login",
                            json={"username": "admin", "password": PASSWORD}).json()["token"]

    context = ssl.create_default_context(cafile=str(config.tls_ca_certificate))
    from websockets.sync.client import connect

    with connect(f"wss://localhost:{port}/ws", ssl=context) as ws:
        ws.send(json.dumps({"type": "auth", "token": token}))
        ready = json.loads(ws.recv(timeout=10))
        assert ready["type"] == "ready"
        assert "status" in ready
        ws.send(json.dumps({"type": "tail", "lines": 5}))
        assert json.loads(ws.recv(timeout=10))["type"] == "console_tail"


def test_wss_rejects_an_unauthenticated_socket(live_tls):
    config, port = live_tls
    import json

    context = ssl.create_default_context(cafile=str(config.tls_ca_certificate))
    from websockets.sync.client import connect

    with connect(f"wss://localhost:{port}/ws", ssl=context) as ws:
        ws.send(json.dumps({"type": "tail", "lines": 5}))
        message = json.loads(ws.recv(timeout=10))
        assert message["type"] == "error"


# ---------------------------------------------------------------- redirect
def test_http_listener_only_redirects_and_refuses_api_calls():
    app = create_redirect_app(8765)
    from fastapi.testclient import TestClient

    with TestClient(app) as client:
        response = client.get("/api/status", follow_redirects=False)
        assert response.status_code == 308
        assert response.headers["location"].startswith("https://")
        # a POST is refused rather than redirected, so credentials are never
        # re-sent by a client that follows the redirect
        refused = client.post("/api/auth/login", json={"username": "a", "password": "b"})
        assert refused.status_code == 400
        assert "HTTPS" in refused.json()["detail"]
