package io.github.peyoteheadlights.mcsc.core

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonPrimitive

/**
 * Every word the app shows, from mobile/shared/strings.json: the dashboard's
 * own table (agent/web/js/strings.js) plus the app's "mobile.*" entries,
 * generated by mobile/tools/generate.py. Each key has a Simple and a
 * Technical version; a translation can replace some keys and the rest stay
 * English, exactly as in the dashboard (docs/translating.md).
 */
class Strings(
    private val english: Map<String, List<String>>,
    private val translated: Map<String, List<String>> = emptyMap(),
) {
    @Volatile
    var technical: Boolean = false

    fun has(key: String): Boolean = key in english

    fun t(key: String, vararg values: Pair<String, Any?>): String {
        val entry = translated[key]?.takeIf { it.size == 2 && it.all(String::isNotEmpty) }
            ?: english[key]
            ?: return key
        var text = entry[if (technical) 1 else 0]
        for ((name, value) in values) {
            if (value != null) text = text.replace("{$name}", value.toString())
        }
        return text
    }

    /** "1 player" / "3 players": key.one and key.other entries. */
    fun tn(key: String, count: Int, vararg values: Pair<String, Any?>): String =
        t("$key.${if (count == 1) "one" else "other"}", "count" to count, *values)

    companion object {
        fun parse(text: String): Map<String, List<String>> {
            val root = Json.parseToJsonElement(text) as JsonObject
            return root.mapNotNull { (key, value) ->
                val pair = (value as? JsonArray)?.mapNotNull { it.jsonPrimitive.contentOrNull }
                if (pair != null && pair.size == 2) key to pair else null
            }.toMap()
        }
    }
}
