import Foundation

/// Every word the app shows, from mobile/shared/strings.json: the dashboard's
/// own table (agent/web/js/strings.js) plus the app's "mobile.*" entries,
/// generated by mobile/tools/generate.py. Each key has a Simple and a
/// Technical version; a translation can replace some keys and the rest stay
/// English, exactly as in the dashboard (docs/translating.md).
public final class Strings: @unchecked Sendable {
    private let english: [String: [String]]
    private let translated: [String: [String]]

    private let lock = NSLock()
    private var isTechnical = false

    public init(_ english: [String: [String]], translated: [String: [String]] = [:]) {
        self.english = english
        self.translated = translated
    }

    /// Technical wording instead of Simple.
    public var technical: Bool {
        get {
            lock.lock()
            defer { lock.unlock() }
            return isTechnical
        }
        set {
            lock.lock()
            isTechnical = newValue
            lock.unlock()
        }
    }

    public func has(_ key: String) -> Bool { english[key] != nil }

    /// The words for `key`, with each {name} replaced by its value. A key
    /// that isn't in the table reads as itself, so it is noticed.
    public func t(_ key: String, _ values: [String: CustomStringConvertible] = [:]) -> String {
        var entry: [String]? = nil
        if let local = translated[key], local.count == 2, local.allSatisfy({ !$0.isEmpty }) {
            entry = local
        } else {
            entry = english[key]
        }
        guard let pair = entry, pair.count == 2 else { return key }
        var text = pair[technical ? 1 : 0]
        for (name, value) in values {
            text = text.replacingOccurrences(of: "{\(name)}", with: value.description)
        }
        return text
    }

    /// "1 player" / "3 players": key.one and key.other entries.
    public func tn(_ key: String, count: Int, _ values: [String: CustomStringConvertible] = [:]) -> String {
        var all = values
        all["count"] = count
        return t("\(key).\(count == 1 ? "one" : "other")", all)
    }

    /// strings.json: {"key": ["Simple", "Technical"], ...}.
    public static func parse(_ data: Data) -> [String: [String]] {
        guard let root = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            return [:]
        }
        var out: [String: [String]] = [:]
        for (key, value) in root {
            if let pair = value as? [String], pair.count == 2 {
                out[key] = pair
            }
        }
        return out
    }
}
