"""The safe downloader: one module for every file and list the app fetches.

Rules, the same for every source (Mojang, Fabric, Quilt, Forge, NeoForge,
Paper, Purpur, Modrinth, GeyserMC):

  * HTTPS only, and only from the official hosts in ALLOWED_HOSTS. A
    redirect is followed only to another allowed host.
  * a size cap on every response
  * the file is checked against the checksum its source publishes (SHA-512,
    SHA-256, SHA-1 or, for Purpur, MD5) before anything uses it. A
    mismatch discards the file.
  * when the source publishes no checksum the file is still accepted where
    the caller allows it, but recorded as "unverified", never as checked
  * files are written to a temporary name and only renamed into place once
    they are complete and checked, so a failed download leaves nothing
    half-written behind

Nothing downloaded here is executed by this module.
"""

from __future__ import annotations

import asyncio
import hashlib
import logging
import os
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any
from urllib.parse import urljoin, urlparse

import httpx

from . import __version__

if TYPE_CHECKING:
    from .jobs import JobHandle

log = logging.getLogger("msc.downloads")

ALLOWED_HOSTS = frozenset(
    {
        # Mojang
        "piston-meta.mojang.com",
        "piston-data.mojang.com",
        "launchermeta.mojang.com",
        "launcher.mojang.com",
        # Fabric
        "meta.fabricmc.net",
        "maven.fabricmc.net",
        # Quilt
        "meta.quiltmc.org",
        "maven.quiltmc.org",
        # Forge
        "maven.minecraftforge.net",
        "files.minecraftforge.net",
        # NeoForge
        "maven.neoforged.net",
        # Paper
        "fill.papermc.io",
        "fill-data.papermc.io",
        "api.papermc.io",
        # Purpur
        "api.purpurmc.org",
        # Modrinth
        "api.modrinth.com",
        "cdn.modrinth.com",
        "cdn-raw.modrinth.com",
        # GeyserMC
        "download.geysermc.org",
    }
)

MAX_LIST_BYTES = 20 * 1024 * 1024  # a version list or API answer
MAX_FILE_BYTES = 300 * 1024 * 1024  # one server jar, installer or mod
CHUNK = 256 * 1024
USER_AGENT = (
    f"minecraft-server-controller/{__version__} "
    "(+https://github.com/peyoteheadlights/minecraft-server-controller)"
)
# Strongest first: when a source publishes several, the strongest is checked.
ALGORITHMS = ("sha512", "sha256", "sha1", "md5")

# Tests replace this with an httpx.MockTransport. Nothing else may set it.
TRANSPORT: httpx.AsyncBaseTransport | None = None


class DownloadError(RuntimeError):
    """A download or list could not be fetched or did not check out. The
    message is written for the person reading it."""


@dataclass(frozen=True)
class FileSpec:
    """One file to fetch. ``name`` is generated by the app, never taken
    from a request or a server's answer."""

    url: str
    name: str
    sha512: str | None = None
    sha256: str | None = None
    sha1: str | None = None
    md5: str | None = None
    size: int | None = None
    # When False, a source that publishes no checksum is refused instead
    # of recorded as unverified.
    allow_unverified: bool = True
    max_bytes: int = MAX_FILE_BYTES

    def expected(self) -> tuple[str, str] | None:
        for algorithm in ALGORITHMS:
            value = getattr(self, algorithm)
            if value:
                return algorithm, str(value).strip().lower()
        return None


@dataclass
class FetchedFile:
    path: Path
    size: int
    sha256: str
    verified: bool
    checked_with: str | None  # the algorithm checked, None when unverified
    source: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "file": self.path.name,
            "size": self.size,
            "sha256": self.sha256,
            "verified": self.verified,
            "checked_with": self.checked_with,
            "source": self.source,
        }


def check_url(url: str) -> str:
    """Return the URL if it is HTTPS to an allowed host, else raise."""
    parsed = urlparse(str(url or ""))
    if parsed.scheme != "https":
        raise DownloadError("Only secure (https) downloads are allowed.")
    host = (parsed.hostname or "").lower()
    if host not in ALLOWED_HOSTS:
        raise DownloadError(
            f"Downloads from {host or 'that address'} aren't allowed. "
            "Only official Minecraft, mod loader and Modrinth sites are."
        )
    if parsed.username or parsed.password or parsed.port not in (None, 443):
        raise DownloadError("That download address isn't allowed.")
    return url


def source_name(url: str) -> str:
    return (urlparse(url).hostname or "").lower()


def _client(timeout: float = 60.0) -> httpx.AsyncClient:
    return httpx.AsyncClient(
        timeout=httpx.Timeout(timeout, connect=20.0),
        headers={"User-Agent": USER_AGENT},
        follow_redirects=False,  # redirects are followed by hand, host by host
        transport=TRANSPORT,
    )


def _plain_status(status: int, host: str) -> str:
    if status == 404:
        return f"{host} doesn't have that file (it may have been removed)."
    if status == 429:
        return f"{host} is busy and asked us to slow down. Try again in a minute."
    if status in (401, 403):
        return f"{host} refused the download."
    if status >= 500:
        return f"{host} has a problem right now. Try again later."
    return f"{host} refused the request (error {status})."


async def _send(
    client: httpx.AsyncClient, url: str, stream: bool = False
) -> tuple[httpx.Response, str]:
    """GET ``url``, following up to five redirects between allowed hosts."""
    for _ in range(6):
        check_url(url)
        request = client.build_request("GET", url)
        try:
            response = await client.send(request, stream=stream)
        except httpx.TimeoutException as exc:
            raise DownloadError(f"{source_name(url)} took too long to answer.") from exc
        except httpx.HTTPError as exc:
            raise DownloadError(
                f"Couldn't reach {source_name(url)}. Check the PC's internet connection."
            ) from exc
        if response.is_redirect:
            location = response.headers.get("location", "")
            await response.aclose()
            url = urljoin(url, location)
            continue
        if response.status_code >= 400:
            await response.aclose()
            raise DownloadError(_plain_status(response.status_code, source_name(url)))
        return response, url
    raise DownloadError(
        f"{source_name(url)} kept sending the download somewhere else, so it was stopped."
    )


async def fetch_bytes(url: str, max_bytes: int = MAX_LIST_BYTES) -> bytes:
    async with _client() as client:
        response, final = await _send(client, url, stream=True)
        try:
            data = bytearray()
            async for chunk in response.aiter_bytes():
                data.extend(chunk)
                if len(data) > max_bytes:
                    raise DownloadError(f"{source_name(final)} sent more data than expected.")
            return bytes(data)
        finally:
            await response.aclose()


async def fetch_json(url: str, max_bytes: int = MAX_LIST_BYTES) -> Any:
    data = await fetch_bytes(url, max_bytes)
    try:
        import json

        return json.loads(data.decode("utf-8"))
    except (UnicodeDecodeError, ValueError) as exc:
        raise DownloadError(f"{source_name(url)} sent an answer that couldn't be read.") from exc


async def fetch_text(url: str, max_bytes: int = MAX_LIST_BYTES) -> str:
    data = await fetch_bytes(url, max_bytes)
    return data.decode("utf-8", errors="replace")


async def download(
    spec: FileSpec, folder: Path, job: JobHandle | None = None, label: str | None = None
) -> FetchedFile:
    """Fetch ``spec`` into ``folder`` under ``spec.name``. The file appears
    there only once it is complete and its checksum matched."""
    from .security.paths import safe_join

    expected = spec.expected()
    if expected is None and not spec.allow_unverified:
        raise DownloadError(
            f"{source_name(spec.url)} doesn't publish a checksum for this file, "
            "so it can't be checked. Nothing was installed."
        )
    folder.mkdir(parents=True, exist_ok=True)
    target = safe_join(folder, spec.name)
    temp = target.with_name(f".{target.name}.part")
    digests = {"sha256": hashlib.sha256()}
    if expected and expected[0] != "sha256":
        digests[expected[0]] = hashlib.new(expected[0])
    if job:
        job.step(label or f"Downloading {spec.name}", total=spec.size, unit="bytes")
    size = 0
    try:
        async with _client(timeout=120.0) as client:
            response, final = await _send(client, spec.url, stream=True)
            try:
                if job and spec.size is None:
                    length = response.headers.get("content-length")
                    if length and length.isdigit():
                        job.set_total(int(length), "bytes")
                # Opened and written in a worker thread, so a slow disk
                # never blocks the event loop while a large jar streams in.
                fh = await asyncio.to_thread(temp.open, "wb")
                try:
                    async for chunk in response.aiter_bytes(CHUNK):
                        size += len(chunk)
                        if size > spec.max_bytes:
                            raise DownloadError(
                                f"{spec.name} is bigger than the "
                                f"{spec.max_bytes // (1024 * 1024)} MB limit."
                            )
                        await asyncio.to_thread(fh.write, chunk)
                        for digest in digests.values():
                            digest.update(chunk)
                        if job:
                            job.advance(len(chunk))
                finally:
                    await asyncio.to_thread(fh.close)
            finally:
                await response.aclose()
        if spec.size is not None and size != int(spec.size):
            raise DownloadError(
                f"{spec.name} arrived incomplete ({size} of {spec.size} bytes). Try again."
            )
        checked_with = None
        if expected:
            algorithm, value = expected
            if digests[algorithm].hexdigest().lower() != value:
                raise DownloadError(
                    f"{spec.name} didn't match the checksum {source_name(spec.url)} "
                    "published, so it was thrown away. Try again."
                )
            checked_with = algorithm
        os.replace(temp, target)
    except BaseException:
        temp.unlink(missing_ok=True)
        raise
    result = FetchedFile(
        path=target,
        size=size,
        sha256=digests["sha256"].hexdigest(),
        verified=checked_with is not None,
        checked_with=checked_with,
        source=final,
    )
    log.info(
        "downloaded %s from %s (%d bytes, %s)",
        spec.name,
        source_name(final),
        size,
        checked_with or "unverified",
    )
    return result


async def download_bytes(spec: FileSpec) -> tuple[bytes, FetchedFile]:
    """For small files a caller checks further in memory (a mod jar)."""
    import tempfile

    with tempfile.TemporaryDirectory(prefix="mcsc-dl-") as tmp:
        fetched = await download(spec, Path(tmp))
        data = fetched.path.read_bytes()
    return data, fetched
