/* Every piece of text the dashboard shows, in one table, each with a
   Simple version (everyday words, the default) and a Technical version
   (the precise terms: TPS, MSPT, RSS, -Xmx, TLS). Components look text up
   with t(key, values); nothing user-facing is written inline elsewhere.

   The table between the two markers is plain JSON, so tests can read it:
   tests/test_strings.py checks every entry has both versions with the same
   {placeholders}, and that every key the code uses exists. More languages
   can later live in their own files with this one as the fallback. */

export const STRINGS = /* strings-table */ {
  "app.name": ["Minecraft Server Control", "Minecraft Server Control"],

  "login.username": ["Username", "Username"],
  "login.password": ["Password", "Password"],
  "login.sign_in": ["Sign in", "Sign in"],
  "login.signing_in": ["Signing in…", "Signing in…"],

  "page.servers": ["All servers", "All servers"],
  "page.add_server": ["Add server", "Add a server"],
  "page.overview": ["Overview", "Overview"],
  "page.players": ["Players", "Players"],
  "page.backups": ["Backups", "Backups"],
  "page.mods": ["Mods", "Mods"],
  "page.schedules": ["Schedules", "Schedules"],
  "page.performance": ["Performance", "Performance"],
  "page.console": ["Console", "Console"],
  "page.events": ["Events", "Events"],
  "page.crashes": ["Crashes", "Crashes"],
  "page.server_settings": ["Server settings", "Server settings"],
  "page.app_settings": ["App settings", "Agent settings"],
  "page.security": ["Security", "Security"],

  "nav.server_pages": ["Server pages", "Pages for this server"],
  "nav.app_pages": ["App pages", "Pages for this app"],
  "nav.group_live": ["Live", "Live"],
  "nav.group_manage": ["Manage", "Manage"],
  "nav.group_history": ["History", "History"],

  "tabs.label": ["Servers", "Servers"],
  "tabs.crashed": ["crashed", "crashed"],

  "state.online": ["Online", "Online"],
  "state.offline": ["Offline", "Offline"],
  "state.starting": ["Starting…", "Starting…"],
  "state.stopping": ["Stopping…", "Stopping…"],
  "state.restarting": ["Restarting…", "Restarting…"],
  "state.crashed": ["Crashed", "Crashed"],
  "state.unknown": ["Unknown", "Unknown"],

  "head.app": ["Settings", "Settings"],
  "head.players.one": ["{count} player online", "{count} player online"],
  "head.players.other": ["{count} players online", "{count} players online"],

  "action.start": ["Start", "Start"],
  "action.stop": ["Stop", "Stop"],
  "action.restart": ["Restart", "Restart"],
  "action.restart_now": ["Restart now", "Restart now"],
  "action.starting": ["Starting…", "Starting…"],
  "action.stopping": ["Stopping…", "Stopping…"],
  "action.restarting": ["Restarting…", "Restarting…"],
  "action.cancel": ["Cancel", "Cancel"],
  "action.cancelling": ["Cancelling…", "Cancelling…"],
  "action.confirm": ["Confirm", "Confirm"],
  "action.close": ["Close", "Close"],
  "action.save": ["Save", "Save"],
  "action.saving": ["Saving…", "Saving…"],
  "action.sign_out": ["Sign out", "Sign out"],
  "action.back_up_now": ["Back up now", "Back up now"],
  "action.view_details": ["View details", "View details"],
  "action.show_details": ["Show details", "Show raw details"],
  "action.what_happened": ["What happened?", "What happened?"],
  "action.restart_requested": ["Restarting. Watch the status.", "Restart requested; not yet verified. Watch the status for ONLINE."],

  "confirm.stop_title": ["Stop the server?", "Stop the server?"],
  "confirm.stop_body": ["Players are disconnected. The world saves first.", "Players are disconnected. The server runs save-all and stop, then the process is waited for."],
  "confirm.restart_title": ["Restart the server?", "Restart the server?"],
  "confirm.restart_body": ["Players are disconnected for a minute or two. The world saves first.", "Players are disconnected. The server is stopped cleanly (save-all, stop) and started again."],

  "error.unreachable": ["Can't reach the PC. Check it's on and online.", "The agent did not answer. Check the PC is on and Tailscale is connected."],
  "error.session_ended": ["You were signed out. Please sign in again.", "Your session ended. Please sign in again."],
  "error.request_failed": ["Something went wrong (code {status}).", "Request failed (HTTP {status})."],

  "value.unknown": ["Unknown", "Unknown"],
  "value.yes": ["Yes", "Yes"],
  "value.no": ["No", "No"],

  "time.days_hours": ["{d}d {h}h", "{d}d {h}h"],
  "time.hours_minutes": ["{h}h {m}m", "{h}h {m}m"],
  "time.minutes": ["{m}m", "{m}m"],
  "time.seconds": ["{s}s", "{s}s"],
  "time.ago": ["{duration} ago", "{duration} ago"],
  "time.in": ["in {duration}", "in {duration}"],
  "time.never": ["Never", "Never"],

  "status.loading": ["Loading…", "Loading…"],

  "jobs.working": ["working", "working"],
  "jobs.running.one": ["{count} task running", "{count} job running"],
  "jobs.running.other": ["{count} tasks running", "{count} jobs running"],

  "live.connected": ["Live", "Live"],
  "live.reconnecting": ["Reconnecting…", "Reconnecting…"],
  "live.connected_title": ["Updates show as they happen.", "WebSocket connected: events arrive live."],
  "live.reconnecting_title": ["Lost the PC. Trying again.", "WebSocket disconnected; reconnecting with backoff."],
  "live.connected_announce": ["Live updates on.", "Live updates connected."],
  "live.lost_announce": ["Live updates lost. Reconnecting.", "Live updates lost. Reconnecting."],
  "live.state_announce": ["Server is now {state}.", "Server is now {state}."],

  "event.server_started": ["The server started.", "The server started."],
  "event.server_stopped": ["The server stopped.", "The server stopped."],
  "event.server_crashed": ["The server crashed.", "The server crashed."],
  "event.server_crashed_code": ["The server crashed (code {code}).", "The server crashed (exit code {code})."],
  "event.crash_loop": ["The server keeps crashing. Auto restarts are paused.", "Crash loop detected: automatic restarts are paused."],
  "event.server_recovered": ["The server is back after a crash.", "The server is back online after a crash."],
  "event.other_crashed": ["{name} crashed.", "{name} crashed."],
  "event.other_crash_loop": ["{name} keeps crashing. Auto restarts are paused.", "{name}: crash loop detected, automatic restarts paused."],
  "event.show_server": ["Show {name}", "Show {name}"],

  "hero.up_for": ["Up for {duration}", "Up {duration}"],
  "hero.version": ["Minecraft {mc}", "Minecraft {mc}"],
  "hero.version_loader": ["Minecraft {mc} with Fabric {loader}", "Minecraft {mc}, Fabric Loader {loader}"],
  "hero.so_far": ["({s} seconds so far)", "({s}s elapsed)"],
  "hero.stopping": ["Stopping. Saving the world.", "Stopping. The world is being saved."],
  "hero.restarting": ["Restarting.", "Restarting."],
  "hero.crashed": ["The server crashed.", "The server crashed."],
  "hero.exit_code": ["Exit code {code}.", "Exit code {code}."],
  "hero.cause": ["Cause: {cause}.", "Cause: {cause}."],
  "hero.likely_cause": ["Probably because {cause}.", "Likely cause: {cause}."],
  "hero.possible_cause": ["Maybe because {cause}.", "Possible cause: {cause}."],
  "hero.cause_unknown": ["The log doesn't show the cause.", "Cause not identified from the crash report or log."],
  "hero.reading_crash": ["Reading the crash log…", "Analysing the crash report…"],
  "hero.restart_paused": ["Auto restarts are paused.", "Auto-restart is blocked."],
  "hero.restart_cancelled": ["Auto restart cancelled.", "Pending auto-restart was cancelled."],
  "hero.restarting_in": ["Restarting in {s} seconds.", "Auto-restart in {s}s."],
  "hero.starting_now": ["Restarting now.", "Auto-restart firing now."],
  "hero.force_stopped": ["Forced to stop: it didn't stop in time.", "Force-killed after the stop timeout."],
  "hero.stopped": ["Stopped.", "Stopped."],
  "hero.not_running": ["Not running.", "Not running."],
  "hero.last_run": ["Last ran {versions}.", "Last run: {versions}."],
  "hero.unknown": ["State not known yet.", "State UNKNOWN: no status reading yet."],

  "starting.java": ["Starting Java", "Starting the JVM"],
  "starting.mods": ["Loading mods", "Loading mods"],
  "starting.server": ["Starting server", "Starting the Minecraft server"],
  "starting.world": ["Loading world", "Preparing spawn area"],

  "notice.maintenance": ["Maintenance mode is on.", "Maintenance mode is on."],
  "notice.maintenance_detail": ["Auto restarts and schedules are paused.", "Auto-restart, crash recovery and scheduled tasks are suspended."],
  "notice.turn_off": ["Turn off", "Turn off"],
  "notice.turning_off": ["Turning off…", "Turning off…"],
  "notice.restart_paused": ["Auto restarts are paused.", "Auto-restart is blocked."],
  "notice.restart_paused_detail": ["{reason}", "{reason}"],
  "notice.allow_restarts": ["Allow restarts", "Clear the block"],
  "notice.allowing": ["Allowing…", "Allowing…"],
  "notice.restarts_allowed": ["Auto restarts are back on.", "Auto-restart block cleared."],

  "overview.stats_label": ["At a glance", "Server at a glance"],
  "overview.players": ["Players", "Players"],
  "overview.of_max": ["of {max}", "of {max}"],
  "overview.players_waiting": ["Waiting for first count", "Waiting for the first list reading"],
  "overview.speed": ["Game speed", "TPS"],
  "overview.speed_unit": ["of 20", "/ 20"],
  "overview.mspt_now": ["{ms} ms per tick", "{ms} ms per tick"],
  "overview.via": ["via {command}", "via {command}"],
  "overview.speed_detecting": ["Finding how to read speed…", "Detecting a TPS command…"],
  "overview.speed_unavailable": ["This server doesn't report speed", "No TPS command works on this server"],
  "overview.speed_off": ["Speed readings off", "TPS polling disabled"],
  "overview.speed_waiting": ["Waiting for first reading", "Waiting for the first TPS reading"],
  "overview.when_running": ["Shown while running", "Read while ONLINE"],
  "overview.memory": ["Memory used", "Server memory (RSS)"],
  "overview.of_limit": ["of {limit} max", "of {limit} -Xmx"],
  "overview.not_measured": ["Not measured yet", "No reading yet"],
  "overview.cpu": ["CPU use", "PC CPU"],
  "overview.cpu_note": ["Whole PC", "All processes, all cores"],
  "overview.last_backup": ["Last backup", "Last backup"],
  "overview.next_task": ["Next task", "Next scheduled job"],
  "overview.players_online": ["Players online", "Players online"],
  "overview.nobody_online": ["Nobody online.", "Nobody is online."],
  "overview.players_unknown": ["Players not known", "Player list not read"],
  "overview.players_unknown_hint": ["Shown once the server is running.", "Read with the list command while ONLINE."],
  "overview.online_for": ["online {duration}", "online {duration}"],
  "overview.recommendations": ["Suggestions", "Recommendations"],
  "overview.details": ["Details", "Details"],
  "overview.minecraft": ["Minecraft", "Minecraft"],
  "overview.loader": ["Fabric Loader", "Fabric Loader"],
  "overview.java": ["Java", "Java"],
  "overview.port": ["Port", "Port"],
  "overview.mods": ["Mods", "Mods"],
  "overview.disk_free": ["Free space", "Disk free"],
  "overview.detected_on_start": ["Found on start", "Detected on next start"],
  "overview.recent_console": ["Recent console", "Recent console output"],
  "overview.open_console": ["Open console", "Open the console"],

  "summary.last_hour": ["Last hour:", "Last hour:"],
  "summary.speed": ["average {avg}, lowest {low}", "avg {avg} TPS, min {low}"],
  "summary.samples": ["{n} readings", "{n} samples"],
  "summary.not_yet": ["No readings in the last hour.", "No samples in the last hour."],
  "summary.memory_trend": ["from {from} to {to}", "{from} → {to}"],
  "summary.memory_peak": ["peak {peak}", "peak {peak}"],
  "summary.limit": ["{limit} max", "limit {limit} (-Xmx)"],
  "summary.no_limit": ["No memory limit set.", "No -Xmx set."],
  "summary.cpu": ["average {avg}%, peak {high}%", "avg {avg}%, max {high}%"],
  "summary.players_unknown": ["Players not known yet.", "Player list not read yet."],
  "summary.nobody": ["Nobody online.", "Nobody is online."],

  "backup.never": ["No backups yet", "No backups yet"],
  "backup.never_hint": ["Make one so you can undo mistakes.", "No backup exists for this server."],
  "backup.checked": ["Checked", "Verified"],
  "backup.unchecked": ["Not checked", "Unverified"],
  "backup.failed": ["Failed", "Failed"],
  "backup.working": ["Backing up…", "Backing up…"],
  "backup.done": ["Backup saved: {name}", "Backup created and verified: {name}"],

  "schedule.nothing": ["Nothing scheduled", "Nothing scheduled"],
  "schedule.add": ["Add schedule", "Add a schedule"],
  "schedule.next": ["{task} {when}", "{task} {when}"],
  "schedule.open": ["All schedules", "See all schedules"],

  "task.start": ["Start server", "Start the server"],
  "task.stop": ["Stop server", "Stop the server"],
  "task.restart": ["Restart server", "Restart the server"],
  "task.backup": ["Back up", "Back up"],
  "task.log_cleanup": ["Clear old logs", "Log cleanup"],
  "task.notify": ["Send message", "Notify"],
  "task.maintenance_on": ["Maintenance mode on", "Turn on maintenance mode"],
  "task.maintenance_off": ["Maintenance mode off", "Turn off maintenance mode"],

  "rec.none": ["No suggestions now.", "No recommendations fire right now."],
  "rec.snooze": ["Not now", "Not now"],
  "rec.snooze_title": ["Hide until something changes", "Snooze until the evidence changes"],
  "rec.dismiss": ["Don't show again", "Don't show again"],
  "rec.dismiss_title": ["Never show this here", "Dismiss permanently for this server"],
  "rec.show_again": ["Show again", "Show again"],
  "rec.hidden.one": ["{count} hidden suggestion", "{count} hidden recommendation"],
  "rec.hidden.other": ["{count} hidden suggestions", "{count} hidden recommendations"],

  "cause.OutOfMemoryError": ["the server ran out of memory", "OutOfMemoryError: the Java heap ran out"],
  "cause.JavaHeapError": ["Java couldn't get the memory set for it", "the JVM could not reserve the -Xmx heap"],
  "cause.JavaVersionIncompatible": ["the wrong Java version is installed", "the Java version is incompatible with this Minecraft version"],
  "cause.ModDependencyError": ["a mod needs another mod, or a different version of it", "a mod dependency is missing or out of range"],
  "cause.MissingMod": ["a needed mod isn't installed", "a required mod is not installed"],
  "cause.IncompatibleMod": ["two mods don't work together", "two installed mods don't work together"],
  "cause.MixinError": ["a mod failed to load into the game", "a mixin failed to apply"],
  "cause.FabricLoaderError": ["Fabric failed to start", "Fabric Loader refused to start"],
  "cause.ClassNotFoundException": ["a mod is for a different game version", "ClassNotFoundException: a mod targets another game version"],
  "cause.NoSuchMethodError": ["mod versions don't match each other", "NoSuchMethodError: mismatched mod versions"],
  "cause.WorldChunkError": ["world data couldn't be loaded or saved", "chunk or region data could not be read or written"],
  "cause.DiskStorageError": ["the disk is full or can't be written to", "the disk is full or can't be written to"],
  "cause.PortInUse": ["another program is using the server's port", "the server port is already bound"],
  "cause.EulaNotAccepted": ["the Minecraft EULA isn't accepted", "the Minecraft EULA has not been accepted"],
  "cause.NetworkError": ["a network error", "a network error"],
  "cause.ServerThreadCrash": ["an error in the game loop", "an exception on the main server thread"],

  "servers.none": ["No servers yet", "No servers yet"],
  "servers.none_hint": ["Use the + tab to add a server.", "Add one with the + tab or in config.yaml."],
  "servers.players": ["Players", "Players"],
  "servers.players_of": ["{n} of {max}", "{n} of {max}"],
  "servers.uptime": ["Up for", "Uptime"],
  "servers.not_running": ["Not running", "Not running"],
  "servers.port": ["Port", "Port"],

  "add.existing": ["Add a server already on this PC", "Add a server that's already on this PC"],
  "add.existing_hint": ["Pick the folder with the server's .jar and world.", "The server directory: holds the server jar, server.properties and the world."],
  "add.name": ["Name", "Name"],
  "add.folder": ["Folder", "Server directory"],
  "add.more_options": ["More options", "Advanced"],
  "add.jar": ["Server file", "Server jar"],
  "add.jar_hint": ["Leave blank to find it.", "Leave empty to auto-detect the jar in the directory."],
  "add.submit": ["Add server", "Add server"],
  "add.adding": ["Adding…", "Adding…"],
  "add.need_name_and_folder": ["Enter a name and folder.", "Give the server a name and a folder."],
  "add.added": ["{name} added.", "{name} added."],
  "add.color_used": ["{color} (in use)", "{color} (already used)"],

  "color.blue": ["Blue", "Blue"],
  "color.orange": ["Orange", "Orange"],
  "color.green": ["Green", "Green"],
  "color.crimson": ["Crimson", "Crimson"],
  "color.violet": ["Violet", "Violet"],
  "color.amber": ["Amber", "Amber"],
  "color.teal": ["Teal", "Teal"],
  "color.magenta": ["Magenta", "Magenta"],
  "color.cyan": ["Cyan", "Cyan"],
  "color.olive": ["Olive", "Olive"],
  "color.rose": ["Rose", "Rose"],
  "color.indigo": ["Indigo", "Indigo"],

  "theme.system": ["Match my device", "System"],
  "theme.light": ["Light", "Light"],
  "theme.dark": ["Dark", "Dark"],
  "theme.graphite": ["Graphite", "Graphite"],
  "theme.contrast": ["High contrast", "High contrast"],

  "mode.simple": ["Simple", "Simple"],
  "mode.simple_hint": ["Plain words. Extra details stay hidden.", "Everyday words. Details stay tucked away until you open them."],
  "mode.technical": ["Technical", "Technical"],
  "mode.technical_hint": ["Exact terms (TPS, MSPT, -Xmx), more numbers, and advanced sections open.", "Exact terms (TPS, MSPT, -Xmx), more numbers, and advanced sections open."],

  "appset.appearance": ["Appearance", "Appearance"],
  "appset.theme": ["Theme", "Theme"],
  "appset.detail": ["Detail level", "Display mode"],
  "appset.mode": ["Detail level", "Display mode"],
  "appset.alerts": ["Alerts", "Alerts"],
  "appset.discord": ["Discord", "Discord"],
  "appset.email": ["Email", "Email"],
  "appset.discord_missing": ["Add the Discord link to .env on the PC first.", "Set DISCORD_WEBHOOK_URL in .env first."],
  "appset.email_missing": ["Add email details to .env on the PC first.", "Set the SMTP_* values in .env first."],
  "appset.send_test": ["Send test", "Send a test"],
  "appset.sending": ["Sending…", "Sending…"],
  "appset.test_sent": ["Test sent.", "Test sent."],
  "appset.test_failed": ["Test failed. Check .env.", "Test failed. Check the .env settings and the agent log."],
  "appset.alert_details": ["When to alert", "Thresholds and events"],
  "appset.cpu_alert": ["Alert when CPU use is above (%)", "CPU alert threshold (%)"],
  "appset.ram_alert": ["Alert when PC memory is above (%)", "RAM alert threshold (%)"],
  "appset.disk_alert": ["Alert when free space is below (GB)", "Disk free threshold (GB)"],
  "appset.tps_alert": ["Alert when game speed is below (of 20)", "TPS minimum"],
  "appset.mspt_alert": ["Alert when a tick takes over (ms)", "MSPT maximum (ms)"],
  "appset.repeat_alert": ["Gap between repeat alerts (seconds)", "Minimum interval between repeats (s)"],
  "appset.which_events": ["Alert me when", "Events"],
  "appset.save_alerts": ["Save alerts", "Save alert settings"],
  "appset.secrets_note": ["Links and passwords stay in .env on the PC, never here.", "Secrets (webhook URL, SMTP password) are read from .env only and never sent to the browser."],
  "appset.maintenance": ["Maintenance mode", "Maintenance mode"],
  "appset.maintenance_label": ["Pause auto restarts and schedules on all servers", "Suspend auto-restart and schedules (all servers)"],
  "appset.maintenance_on": ["Maintenance mode is on.", "Maintenance mode is on."],
  "appset.maintenance_off": ["Maintenance mode is off.", "Maintenance mode is off."],
  "appset.startup": ["Start with Windows", "Windows startup task"],
  "appset.startup_hint": ["Checks if this app starts when the PC turns on. It only checks.", "Inspects the scheduled task (read-only)."],
  "appset.startup_check": ["Check now", "Inspect"],
  "appset.startup_asking": ["Checking…", "Inspecting…"],
  "appset.check": ["Check", "Check"],
  "appset.result": ["Result", "Result"],

  "settings.saved": ["Settings saved.", "Settings saved."],
  "settings.nothing_changed": ["Nothing changed.", "Nothing changed."],

  "alert_event.server_started": ["Server started", "The server started"],
  "alert_event.server_stopped": ["Server stopped", "The server stopped"],
  "alert_event.server_crashed": ["Server crashed", "The server crashed"],
  "alert_event.server_restarted": ["Server restarted", "The server restarted"],
  "alert_event.server_recovered": ["Server back after a crash", "The server came back after a crash"],
  "alert_event.player_joined": ["Player joined", "A player joined"],
  "alert_event.player_left": ["Player left", "A player left"],
  "alert_event.high_ram": ["PC memory nearly full", "High RAM"],
  "alert_event.high_cpu": ["CPU use high", "High CPU"],
  "alert_event.low_disk": ["Low disk space", "Low disk"],
  "alert_event.low_tps": ["Game running slowly", "Low TPS"],
  "alert_event.high_mspt": ["Ticks taking too long", "High MSPT"],
  "alert_event.backup_completed": ["Backup finished", "A backup finished"],
  "alert_event.backup_failed": ["Backup failed", "A backup failed"],
  "alert_event.mod_installed": ["Mod installed", "A mod was installed"],
  "alert_event.mod_removed": ["Mod removed", "A mod was removed"],
  "alert_event.mod_updated": ["Mod updated", "A mod was updated"],
  "alert_event.mod_dependency_problem": ["Mod missing a needed mod", "Mod dependency problem"],
  "alert_event.auth_failure": ["Failed sign-in", "Authentication failure"],
  "alert_event.maintenance_mode": ["Maintenance mode on or off", "Maintenance mode turned on or off"],
  "alert_event.certificate_expiring": ["HTTPS certificate expiring soon", "TLS certificate expiring"],
  "alert_event.servers_changed": ["Server added or removed", "A server was added or removed"],
  "alert_event.cpu_cores_failed": ["CPU core setting failed", "CPU affinity could not be applied"],

  "startup.registered_correctly": ["Starts with Windows", "Registered correctly"],
  "startup.not_registered": ["Doesn't start with Windows", "Not registered"],
  "startup.problems_found": ["Set to start with Windows, but has a problem", "Problems found"],
  "startup.unsupported": ["Windows only", "Unsupported (not Windows)"],
  "startup.registered": ["Startup entry", "Task registered"],
  "startup.found": ["Found", "Found"],
  "startup.not_found": ["Not found", "Not found"],
  "startup.mode": ["Starts when", "Trigger"],
  "startup.at_boot": ["The PC turns on", "At boot"],
  "startup.at_logon": ["You sign in to Windows", "At logon"],
  "startup.points_here": ["Points to this app", "Points to the current install"],
  "startup.last_run": ["Last ran", "Last run time"],
  "startup.last_start": ["Last start", "Last recorded startup"],
  "startup.last_start_value": ["{when} ({by})", "{when} ({by})"],
  "startup.none": ["None", "None recorded"],
  "startup.initialised": ["Started fully", "Controller initialised"],
  "startup.mechanism": ["Method", "Mechanism"],
  "startup.command": ["Command", "Command"],
  "startup.folder": ["Folder", "Working directory"],
  "startup.last_result": ["Last result", "Last result"],

  "serverset.identity": ["Name and color", "Name and color"],
  "serverset.name": ["Name", "Name"],
  "serverset.color": ["Color", "Color"],
  "serverset.custom_color": ["Any color", "Custom color"],
  "serverset.save_identity": ["Save name and color", "Save name and color"],
  "serverset.folder": ["Folder: {folder}", "Directory: {folder}"],
  "serverset.crashes": ["When it crashes", "Crash recovery"],
  "serverset.auto_restart": ["Restart after a crash", "Auto-restart after a crash"],
  "serverset.crash_details": ["More options", "Advanced"],
  "serverset.restart_delay": ["Wait before restart (seconds)", "Restart delay (s)"],
  "serverset.max_crashes": ["Stop after this many crashes", "Max crashes in window"],
  "serverset.max_crashes_hint": ["…within {minutes} minutes. Then auto restarts pause until you allow them.", "Within {minutes} min; then auto-restart is blocked until cleared."],
  "serverset.memory": ["Memory", "Memory"],
  "serverset.memory_limit": ["Max memory (GB)", "Max heap -Xmx (GB)"],
  "serverset.memory_hint": ["Leave enough for Windows and other programs.", "Sets -Xmx in the JVM arguments. Applies on next start."],
  "serverset.memory_unset": ["No limit set. Java picks one.", "No -Xmx set: the JVM default applies."],
  "serverset.launch_args": ["Java options", "JVM arguments"],
  "serverset.jvm_args": ["Java options", "JVM arguments"],
  "serverset.jvm_args_hint": ["One line. Used from the next start.", "Space-separated. Applies on next start."],
  "serverset.cpu": ["CPU cores", "CPU affinity"],
  "serverset.cpu_unreadable": ["Couldn't read this PC's cores.", "Logical core count unavailable."],
  "serverset.all_cores": ["All cores ({count})", "All logical cores ({count})"],
  "serverset.core": ["Core {n}", "Core {n}"],
  "serverset.core_shared": ["also used by {names}", "shared with {names}"],
  "serverset.cores_now": ["Using {cores} now.", "Applied affinity: {cores}."],
  "serverset.cores_unknown": ["Cores in use now unknown: {reason}", "Applied affinity unknown: {reason}"],
  "serverset.every_core": ["all cores", "all cores"],
  "serverset.half_cores": ["Pick half", "Select half"],
  "serverset.pick_a_core": ["Pick at least one core.", "Pick at least one core."],
  "serverset.cores_applied": ["Saved and applied.", "Saved and applied to the running process."],
  "serverset.cores_next_start": ["Saved. Used from the next start.", "Saved; applied on next start."],
  "serverset.cores_not_applied": ["Saved, but not applied yet: {reason}", "Saved; live apply failed: {reason}"],
  "serverset.backups": ["Backups", "Backups"],
  "serverset.keep_daily": ["Daily backups to keep", "keep_daily"],
  "serverset.keep_weekly": ["Weekly backups to keep", "keep_weekly"],
  "serverset.keep_monthly": ["Monthly backups to keep", "keep_monthly"],
  "serverset.timing": ["Start and stop limits", "Timeouts"],
  "serverset.start_timeout": ["Stop trying to start after (seconds)", "Start timeout (s)"],
  "serverset.stop_timeout": ["Force stop after (seconds)", "Stop timeout (s)"],
  "serverset.stop_timeout_hint": ["If it hasn't stopped by then, it's forced to stop.", "After this the process is killed."],
  "serverset.remove": ["Remove from list", "Remove server"],
  "serverset.remove_hint": ["Removes it from the dashboard. Its folder, world and backups stay.", "Unregisters the server. Files, worlds and backups are not touched."],
  "serverset.remove_last": ["The only server can't be removed.", "The last server cannot be removed."],
  "serverset.remove_button": ["Remove from list", "Remove"],
  "serverset.remove_title": ["Remove {name}?", "Remove {name}?"],
  "serverset.remove_body": ["It leaves the dashboard. Nothing is deleted.", "Unregisters the server; no files are deleted."],
  "serverset.remove_confirm": ["Remove", "Remove"],
  "serverset.removed": ["{name} removed.", "{name} removed from the list."],

  "perf.range": ["Time shown", "Time shown"],
  "perf.range_1": ["1 hour", "1h"],
  "perf.range_6": ["6 hours", "6h"],
  "perf.range_24": ["1 day", "24h"],
  "perf.range_168": ["1 week", "7d"],
  "perf.pc_cpu": ["PC CPU use", "PC CPU"],
  "perf.pc_cpu_note": ["All programs", "All processes"],
  "perf.server_cpu": ["Server CPU use", "Server CPU"],
  "perf.server_cpu_note": ["Share of the whole PC", "Java process, % of all cores"],
  "perf.server_cpu_all": ["Can use all cores", "Affinity: all cores"],
  "perf.server_cpu_some": ["Limited to {n} of {total} cores", "Affinity: {n} of {total} cores"],
  "perf.server_memory": ["Server memory", "Server memory (RSS)"],
  "perf.of_limit": ["of {limit} max", "of {limit} -Xmx"],
  "perf.not_running_note": ["Shown while running", "Read while running"],
  "perf.pc_memory": ["PC memory", "PC RAM"],
  "perf.pc_memory_note": ["All programs", "All processes"],
  "perf.disk_free": ["Free space", "Disk free"],
  "perf.on_server_drive": ["On the server's drive", "Server volume"],
  "perf.unknown_because": ["Unknown: {reason}", "Unknown: {reason}"],
  "perf.chart_cpu": ["CPU use", "CPU"],
  "perf.chart_memory": ["Server memory", "Server memory (RSS)"],
  "perf.chart_speed": ["Game speed", "TPS"],
  "perf.chart_players": ["Players", "Players"],
  "perf.chart_mspt": ["Time per tick", "MSPT"],
  "perf.chart_pc_memory": ["PC memory", "PC RAM used"],
  "perf.speed_unit": ["of 20", "ticks/s"],
  "perf.players_unit": ["players", "players"],
  "perf.limit": ["Limit {limit}", "-Xmx {limit}"],
  "perf.mspt_budget": ["50 ms: max per tick", "50 ms budget"],
  "perf.memory_empty": ["Shown while running.", "No samples: the server was not running."],
  "perf.speed_empty": ["No speed readings in this time.", "No TPS samples in this range."],
  "perf.players_empty": ["No player counts in this time.", "No player samples in this range."],
  "perf.storage": ["Disk use", "Storage"],
  "perf.storage_what": ["What", "What"],
  "perf.storage_size": ["Size", "Size"],
  "perf.storage_worlds": ["Worlds", "Worlds"],
  "perf.storage_backups": ["Backups", "Backups"],
  "perf.storage_mods": ["Mods", "Mods"],
  "perf.storage_logs": ["Logs", "Logs"],
  "perf.storage_other": ["Other", "Other"],
  "perf.storage_free": ["Free on drive", "Free on volume"],
  "perf.network": ["Network", "Network"],
  "perf.net_in": ["Received", "Received"],
  "perf.net_out": ["Sent", "Sent"],
  "perf.speed_readings": ["How speed is read", "TPS source"],
  "perf.health": ["Health checks", "Health checks"],

  "health.all_ok": ["All checks passed", "ALL CHECKS VERIFIED"],
  "health.partial": ["Some checks couldn't run", "PARTIALLY VERIFIED"],
  "health.attention": ["Needs attention", "ATTENTION NEEDED"],
  "health.limit": ["limit {limit}", "limit {limit}"],

  "chart.no_samples": ["No data for this time.", "No samples in this range."],
  "chart.aria": ["{title}: latest {latest}, lowest {low}, highest {high}. Use the arrow keys to read each point.", "{title}: latest {latest}, lowest {low}, highest {high}. Use the arrow keys to read each point."],

  "tps.load_failed": ["Couldn't read the speed settings: {error}", "TPS status unavailable: {error}"],
  "tps.status": ["Status", "Status"],
  "tps.command": ["Command", "Command"],
  "tps.detection": ["Chosen", "Detection"],
  "tps.last_reading": ["Last reading", "Last reading"],
  "tps.none_yet": ["None yet", "None yet"],
  "tps.none": ["None", "None"],
  "tps.manual": ["Chosen by you", "Manual"],
  "tps.off": ["Off", "Disabled"],
  "tps.auto": ["Automatic", "Auto-detected"],
  "tps.auto_remembered": ["Automatic (saved)", "Auto (remembered)"],
  "tps.manual_silent": ["None: readings off", "None (polling off)"],
  "tps.state_active": ["Working", "Active"],
  "tps.state_detecting": ["Finding out…", "Detecting…"],
  "tps.state_unavailable": ["Not available", "Unavailable"],
  "tps.state_disabled": ["Off", "Disabled"],
  "tps.state_idle": ["Waiting for server", "Idle"],
  "tps.configure": ["Set up", "Configure"],
  "tps.change": ["Change", "Change command"],
  "tps.detect_again": ["Find again", "Re-detect"],
  "tps.detecting": ["Finding…", "Detecting…"],
  "tps.needs_online": ["Start the server first", "Requires ONLINE"],
  "tps.dialog_title": ["How to read game speed", "TPS command"],
  "tps.dialog_body": ["Minecraft doesn't share its speed. Pick how to ask, or let the app find out.", "Command sent through the console to read TPS. Auto tries the known ones in order."],
  "tps.opt_auto": ["Find out automatically", "Auto-detect"],
  "tps.opt_tick": ["Built in (Minecraft 1.20.3+)", "tick query (vanilla 1.20.3+)"],
  "tps.opt_carpet": ["Carpet mod", "tps (Carpet)"],
  "tps.opt_spark": ["Spark mod", "spark tps"],
  "tps.opt_custom": ["Something else…", "Custom…"],
  "tps.opt_off": ["Don't read speed", "Off"],
  "tps.custom_placeholder": ["command", "command"],
  "tps.custom_label": ["Your command", "Custom command"],
  "tps.saved_auto": ["It will find out automatically.", "Set to auto-detect."],
  "tps.saved_off": ["Speed readings off.", "TPS polling disabled."],
  "tps.saved_command": ["Speed read with {command}.", "TPS command set: {command}"],

  "console.empty": ["Nothing here yet", "No output yet"],
  "console.empty_hint": ["Server messages show here while it runs.", "Server stdout appears here while running."],
  "console.no_match": ["No matches", "Nothing matches"],
  "console.no_match_hint": ["No lines contain “{filter}”.", "No lines contain “{filter}”."],
  "console.filter": ["Filter", "Filter"],
  "console.filter_label": ["Show lines containing", "Filter lines"],
  "console.follow": ["Follow", "Auto-scroll"],
  "console.follow_title": ["Show newest lines", "Scroll to new output"],
  "console.pause": ["Pause", "Pause"],
  "console.pause_title": ["Stop new lines for now", "Freeze the view; output keeps buffering"],
  "console.toggle_on": ["{label} on", "{label} on"],
  "console.toggle_off": ["{label} off", "{label} off"],
  "console.copy": ["Copy", "Copy"],
  "console.copy_title": ["Copy shown lines", "Copy visible lines"],
  "console.copied": ["Copied.", "Copied."],
  "console.copy_unavailable": ["This browser blocked copying.", "Clipboard unavailable."],
  "console.download": ["Download", "Download"],
  "console.download_title": ["Save shown lines as a file", "Download visible lines as .log"],
  "console.clear": ["Clear", "Clear"],
  "console.clear_title": ["Clear this view (log file stays)", "Clear the buffer; latest.log is untouched"],
  "console.clearing": ["Clearing…", "Clearing…"],
  "console.cleared": ["Console cleared.", "Console cleared."],
  "console.output_label": ["Server console output", "Server console output"],
  "console.command_placeholder": ["Command, e.g. say hello", "Command (without /)"],
  "console.command_label": ["Command", "Command to send"],
  "console.send": ["Send", "Send"],
  "console.sending": ["Sending…", "Sending…"],
  "console.run_title": ["Run {command}?", "Run {command}?"],
  "console.run": ["Run", "Run"],
  "console.hint": ["Commands go to Minecraft only, never Windows. Risky ones ask first.", "Sent to the server's console only, never to Windows. Commands that affect players ask for confirmation."],
  "console.load_more": ["Show older lines", "Load more"],

  "mods.running_notice": ["The server is {state}. Stop it to change mods.", "Server is {state}: mod changes need it stopped."],
  "mods.stop_first": ["Stop the server to change mods.", "Stop the server before changing mods."],
  "mods.stop_first_short": ["Stop server first", "Stop the server first"],
  "mods.status_ok": ["Working", "OK"],
  "mods.status_warn": ["Check", "Warning"],
  "mods.status_error": ["Problem", "Problem"],
  "mods.status_off": ["Off", "Disabled"],
  "mods.col_mod": ["Mod", "Mod"],
  "mods.col_version": ["Version", "Version"],
  "mods.col_minecraft": ["Minecraft", "Minecraft"],
  "mods.col_status": ["Status", "Status"],
  "mods.col_downloads": ["Downloads", "Downloads"],
  "mods.col_when": ["When", "When"],
  "mods.col_who": ["Who", "Who"],
  "mods.col_action": ["Action", "Action"],
  "mods.col_change": ["Change", "Change"],
  "mods.col_result": ["Result", "Result"],
  "mods.col_saved": ["Saved", "Saved"],
  "mods.update_to": ["Update: {version}", "Update: {version}"],
  "mods.update": ["Update", "Update"],
  "mods.turn_off": ["Turn off", "Disable"],
  "mods.turn_on": ["Turn on", "Enable"],
  "mods.turned_off": ["{name} turned off.", "{name} disabled."],
  "mods.turned_on": ["{name} turned on.", "{name} enabled."],
  "mods.history": ["Versions", "Versions"],
  "mods.remove": ["Remove", "Remove"],
  "mods.none": ["No mods", "No mods installed"],
  "mods.none_hint": ["Search below to add some.", "Search Modrinth below, or put .jar files in the mods folder."],
  "mods.add": ["Add mods", "Add mods"],
  "mods.search": ["Search", "Search"],
  "mods.searching": ["Searching…", "Searching…"],
  "mods.search_placeholder": ["Search mods", "Search Modrinth"],
  "mods.search_label": ["Search mods", "Search Modrinth"],
  "mods.search_hint": ["Showing Fabric mods for Minecraft {version}.", "Results are filtered to Fabric, game version {version}."],
  "mods.nothing_found": ["Nothing found.", "Nothing found."],
  "mods.install": ["Install", "Install"],
  "mods.about_checks": ["How mods are checked", "About the checks"],
  "mods.limits": ["Limits: {limits}", "Limitations: {limits}"],
  "mods.change_history": ["Changes", "Change history"],
  "mods.no_history": ["No changes yet.", "No history."],
  "mods.no_build": ["No version of this mod fits this server.", "No compatible version found."],
  "mods.install_title": ["Install mod?", "Install this mod?"],
  "mods.install_what": ["{name} {version}", "{name} {version}"],
  "mods.install_size": ["Size: {size}", "Size: {size}"],
  "mods.install_minecraft": ["For Minecraft {versions}", "Game versions: {versions}"],
  "mods.install_file": ["File: {file}", "File: {file}"],
  "mods.install_side": ["Server side: {side}", "Server side: {side}"],
  "mods.install_licence": ["Licence: {licence}", "Licence: {licence}"],
  "mods.install_checked": ["The download is checked first.", "The SHA-512 from Modrinth is verified before the file is placed."],
  "mods.install_confirm": ["Install", "Install"],
  "mods.installed_toast": ["{name} {version} installed. Loads at next start.", "Installed {name} {version}. Loaded by Minecraft: not verified until the server starts."],
  "mods.deps_missing": ["This mod needs others. See the list at the top.", "Required dependencies are still missing."],
  "mods.update_title": ["Update {name}?", "Update {name}?"],
  "mods.update_archived": ["The old version is kept so you can go back.", "The current file is archived and can be rolled back."],
  "mods.updated_toast": ["Updated to {version}. Loads at next start.", "Updated to {version}; loaded on next start."],
  "mods.remove_title": ["Remove {name}?", "Remove {name}?"],
  "mods.needed_by": ["{name} needs it ({requires})", "{name} requires it ({requires})"],
  "mods.not_needed": ["No other mod needs it.", "No installed mod depends on it."],
  "mods.remove_kept": ["A copy is kept so you can put it back.", "The file is archived, not deleted."],
  "mods.removed_toast": ["{name} removed.", "{name} removed."],
  "mods.versions_title": ["Versions of {name}", "Archived versions: {name}"],
  "mods.current": ["In use", "Current"],
  "mods.file_missing": ["File missing", "File missing"],
  "mods.rollback": ["Use this version", "Roll back"],
  "mods.rollback_title": ["Use {version}?", "Roll back to {version}?"],
  "mods.rollback_body": ["The current version is kept too.", "The current file is archived first."],
  "mods.rolled_back": ["Now on {version}.", "Rolled back to {version}."],
  "mods.no_versions": ["No saved versions.", "No archived versions."],
  "mods.installed.one": ["{count} mod installed", "{count} mod installed"],
  "mods.installed.other": ["{count} mods installed", "{count} mods installed"],
  "mods.problems.one": ["{count} mod problem", "{count} mod problem"],
  "mods.problems.other": ["{count} mod problems", "{count} mod problems"],
  "mods.install_deps.one": ["Also install the {count} needed mod", "Also install {count} required dependency"],
  "mods.install_deps.other": ["Also install the {count} needed mods", "Also install {count} required dependencies"],

  "deps.checking": ["Checking mod needs…", "Resolving dependencies…"],
  "deps.check_failed": ["Couldn't check mod needs.", "Dependency check failed."],
  "deps.two_names": ["{a} and {b}", "{a} and {b}"],
  "deps.many_names": ["{a}, {b} and {n} more", "{a}, {b} and {n} more"],
  "deps.status_missing": ["Missing", "Missing"],
  "deps.status_incompatible": ["Wrong version", "Wrong version"],
  "deps.status_disabled": ["Turned off", "Disabled"],
  "deps.status_platform_incompatible": ["Won't work here", "Incompatible"],
  "deps.status_unverified": ["Not checked", "Not checked"],
  "deps.status_satisfied": ["Installed", "Installed"],
  "deps.status_platform_ok": ["OK", "OK"],
  "deps.optional": ["Optional", "Optional"],
  "deps.required_by": ["Needed by {names}.", "Required by {names}."],
  "deps.recommended_by": ["Suggested by {names}.", "Recommended by {names}."],
  "deps.version": ["Version: {range}.", "Range: {range}."],
  "deps.installed_version": ["Installed: {version}.", "Installed: {version}."],
  "deps.not_on_modrinth": ["Not on Modrinth. May need adding by hand.", "Not on Modrinth; install manually."],
  "deps.view_on_modrinth": ["View on Modrinth", "View on Modrinth"],
  "deps.all_ok": ["Every mod has what it needs.", "All declared dependencies are installed."],
  "deps.problems": ["Some mods are missing needed mods", "Dependency problems"],
  "deps.install_missing": ["Install missing ({n})", "Install missing dependencies ({n})"],
  "deps.title": ["Required mods", "Dependencies"],
  "deps.optional_title": ["Optional mods ({n})", "Optional dependencies ({n})"],
  "deps.optional_hint": ["Not needed, but can add features.", "Not required; some features may depend on them."],
  "deps.plan_intro": ["These download from Modrinth and are checked first:", "Downloaded from Modrinth and verified against published hashes:"],
  "deps.needed_by": ["Needed by {names}.", "Required by {names}."],
  "deps.range_unchecked": ["Couldn't confirm this version fits.", "Range not verifiable against this version."],
  "deps.nothing_automatic": ["Nothing can be installed automatically.", "Nothing resolvable automatically."],
  "deps.not_automatic": ["Not installed automatically:", "Not resolvable automatically:"],
  "deps.already_installed": ["Already installed: {names}.", "Already installed: {names}."],
  "deps.plan_safety": ["Your mods aren't replaced. Each install can be undone.", "Existing mods are not replaced. Each download is archived and can be rolled back."],
  "deps.planning": ["Checking…", "Checking…"],
  "deps.installing": ["Installing…", "Installing…"],
  "deps.plan_failed": ["Couldn't plan the install. {error}", "Planning failed: {error}"],
  "deps.nothing_title": ["Nothing to install automatically", "Nothing to install automatically"],
  "deps.install_confirm": ["Install {n}", "Install {n}"],
  "deps.installed_toast": ["Installed {names}. They load at next start.", "Installed {names}. Loaded by Minecraft: not verified until the server starts."],
  "deps.failed_toast": ["{name} couldn't be installed. {error}", "{name} failed: {error}"],
  "deps.still_missing": ["Still missing: {names}.", "Still missing: {names}."],
  "deps.install_failed": ["Couldn't install them. {error}", "Install failed: {error}"],
  "deps.missing.one": ["{count} needed mod is missing", "{count} missing dependency"],
  "deps.missing.other": ["{count} needed mods are missing", "{count} missing dependencies"],
  "deps.install_title.one": ["Install {count} mod?", "Install {count} mod?"],
  "deps.install_title.other": ["Install {count} mods?", "Install {count} mods?"],

  "backups.last_change": ["Last change", "Last change"],
  "backups.last_change_body": ["{title}, {when}. Undo restores the copy {backup} made just before.", "{title}, {when}. Undo restores the safety copy {backup} taken just before it."],
  "backups.undo_change": ["Undo change", "Undo this change"],
  "backups.started": ["Backing up. Big worlds take longer.", "Backup started. Large worlds take a while."],
  "backups.verified_toast": ["Backup saved and checked: {name} ({entries} files)", "Backup verified: {name} ({entries} entries)"],
  "backups.save_world": ["Save world", "Run save-all"],
  "backups.save_sent": ["Saving world.", "save-all flush sent"],
  "backups.worlds": ["Worlds", "Worlds"],
  "backups.col_world": ["World", "World"],
  "backups.col_size": ["Size", "Size"],
  "backups.col_modified": ["Last changed", "Last modified"],
  "backups.col_last_backup": ["Last backup", "Last backup"],
  "backups.col_name": ["Name", "Name"],
  "backups.col_type": ["Type", "Type"],
  "backups.col_created": ["Made", "Created"],
  "backups.world_missing": ["Missing", "not present"],
  "backups.list": ["Backups", "Backups"],
  "backups.keeping": ["Old backups delete automatically. Kept: last {daily} days, {weekly} weeks, {monthly} months.", "Retention: {daily} daily, {weekly} weekly, {monthly} monthly."],
  "backups.kind_manual": ["Manual", "manual"],
  "backups.kind_scheduled": ["Scheduled", "scheduled"],
  "backups.kind_safety": ["Safety copy", "safety"],
  "backups.verify": ["Check", "Verify"],
  "backups.checking": ["Checking…", "Verifying…"],
  "backups.verify_ok": ["Backup is complete and OK.", "Backup verified: archive and checksum are intact"],
  "backups.verify_failed": ["Backup is damaged: {reason}", "Verify failed: {reason}"],
  "backups.download": ["Download", "Download"],
  "backups.restore": ["Restore", "Restore"],
  "backups.delete": ["Delete", "Delete"],
  "backups.delete_title": ["Delete {name}?", "Delete {name}?"],
  "backups.delete_body": ["This backup is deleted for good.", "The archive file is deleted from disk. This cannot be undone."],
  "backups.delete_confirm": ["Delete", "Delete backup"],
  "backups.deleted": ["Backup deleted", "Backup deleted"],
  "backups.none": ["No backups yet", "No backups yet"],
  "backups.none_hint": ["Make one so you can undo mistakes.", "Create one with Back up now or a schedule."],
  "backups.preparing": ["Preparing download…", "Preparing download…"],
  "backups.download_failed": ["Download failed", "Download failed"],
  "backups.restore_title": ["Restore backup?", "Restore this backup?"],
  "backups.restore_question": ["Restore {name} from {when}?", "Restore {name} from {when}?"],
  "backups.start_after": ["Start the server after", "Start the server when the restore finishes"],
  "backups.restore_confirm": ["Check and restore", "Verify and restore"],
  "backups.restoring": ["Restoring. Stopping the server first.", "Restoring. The server will stop first."],
  "backups.restored": ["{name} restored. The old world was saved as {safety}.", "Restored {name}. Safety copy: {safety}"],
  "backups.restore_job": ["Restoring {name}", "Restoring {name}"],
  "backups.undo": ["Undo", "Undo"],
  "backups.undo_title": ["Undo change?", "Undo this change?"],
  "backups.undo_body": ["{title} will be undone by restoring {backup}. The server stops first, and a new safety copy is made.", "{title} will be undone by restoring {backup}. The server stops first, and a new safety copy is taken, so this can be undone too."],
  "backups.undoing": ["Undoing. Stopping the server first.", "Undoing. The server will stop first."],
  "backups.undone": ["Undone. {name} is back.", "Undone: {name} is back."],

  "players.online": ["Online now ({count} of {max})", "Online now ({count}/{max})"],
  "players.col_player": ["Player", "Player"],
  "players.col_uuid": ["UUID", "UUID"],
  "players.col_session": ["Playing for", "This session"],
  "players.col_first": ["First seen", "First seen"],
  "players.col_last": ["Last seen", "Last seen"],
  "players.col_sessions": ["Times joined", "Sessions"],
  "players.col_total": ["Total time", "Total playtime"],
  "players.nobody": ["Nobody is online", "Nobody is online"],
  "players.everyone": ["Everyone seen", "Everyone seen on this server"],
  "players.none": ["No players yet", "No players recorded yet"],
  "players.none_hint": ["Players show here after they join.", "Populated from join/leave log lines."],
  "players.no_ip": ["IP addresses are never saved.", "Player IP addresses are deliberately not recorded."],

  "schedules.add": ["Add schedule", "Add a schedule"],
  "schedules.name": ["Name", "Name"],
  "schedules.name_placeholder": ["Nightly backup", "Nightly backup"],
  "schedules.task": ["What to do", "Task"],
  "schedules.repeat": ["Repeat", "Repeat"],
  "schedules.when": ["When", "When"],
  "schedules.kind_daily": ["Every day", "daily"],
  "schedules.kind_weekly": ["Every week", "weekly"],
  "schedules.kind_interval": ["Every few hours", "interval"],
  "schedules.when_placeholder": ["23:00 / sun 04:00 / 6h", "23:00 / sun 04:00 / 6h"],
  "schedules.when_hint": ["Daily: a time like 23:00. Weekly: a day and time like sun 04:00. Every few hours: a gap like 6h.", "daily: HH:MM. weekly: ddd HH:MM. interval: Nh or Nm."],
  "schedules.create": ["Create", "Create schedule"],
  "schedules.created": ["Schedule created", "Schedule created"],
  "schedules.list": ["Schedules", "Schedules"],
  "schedules.col_name": ["Name", "Name"],
  "schedules.col_task": ["Task", "Task"],
  "schedules.col_when": ["When", "When"],
  "schedules.col_next": ["Next run", "Next run"],
  "schedules.col_result": ["Last run", "Last result"],
  "schedules.every_daily": ["Every day at {expr}", "daily {expr}"],
  "schedules.every_weekly": ["Every week, {expr}", "weekly {expr}"],
  "schedules.every_interval": ["Every {expr}", "interval {expr}"],
  "schedules.off": ["Off", "disabled"],
  "schedules.turn_off": ["Turn off", "Disable"],
  "schedules.turn_on": ["Turn on", "Enable"],
  "schedules.run_now": ["Run now", "Run now"],
  "schedules.delete": ["Delete", "Delete"],
  "schedules.delete_title": ["Delete {name}?", "Delete the schedule {name}?"],
  "schedules.delete_body": ["It won't run again. Its backups are kept.", "The schedule is removed. Its past results and backups are kept."],
  "schedules.deleted": ["Schedule deleted", "Schedule deleted"],
  "schedules.none": ["No schedules", "No schedules"],
  "schedules.none_hint": ["Add one above to back up or restart automatically.", "Nothing is scheduled."],

  "events.title": ["Recent events", "Recent events"],
  "events.col_when": ["When", "When"],
  "events.col_type": ["Type", "Type"],
  "events.col_message": ["What happened", "Message"],
  "events.level_error": ["Problem", "error"],
  "events.level_warn": ["Warning", "warn"],
  "events.none": ["No events yet", "No events recorded"],

  "crashes.title": ["Crash history", "Crash history"],
  "crashes.none": ["No crashes.", "No crashes recorded."],
  "crashes.col_when": ["When", "When"],
  "crashes.col_code": ["Exit code", "Exit code"],
  "crashes.col_cause": ["Likely cause", "Likely cause"],
  "crashes.col_confidence": ["How sure", "Confidence"],
  "crashes.details": ["Details", "Details"],
  "crashes.conf_confirmed": ["Certain", "confirmed"],
  "crashes.conf_likely": ["Likely", "likely"],
  "crashes.conf_possible": ["Possible", "possible"],
  "crashes.conf_unknown": ["Not sure", "unknown"],
  "crashes.cause_unknown": ["Not known", "Unknown"],
  "crashes.dialog_title": ["Crash on {when}", "Crash on {when}"],
  "crashes.suspect_mods": ["Mods named in the log: ", "Installed mods mentioned in the log: "],
  "crashes.suspect_hint": [" (being named isn't proof)", " - appearing in a stack trace is not evidence of causing the crash"],
  "crashes.evidence": ["Lines from the log", "Evidence"],
  "crashes.context": ["More about the crash", "Context"],
  "crashes.f_code": ["Exit code", "Exit code"],
  "crashes.f_minecraft": ["Minecraft", "Minecraft"],
  "crashes.f_loader": ["Fabric loader", "Fabric loader"],
  "crashes.f_java": ["Java", "Java"],
  "crashes.f_players": ["Players online", "Players online"],
  "crashes.f_report": ["Crash report", "Crash report"],
  "crashes.f_log": ["Saved log", "Saved log"],
  "crashes.no_players": ["Nobody", "none"],
  "crashes.no_report": ["None written", "none written by Minecraft"],
  "crashes.rule_match": ["A best guess from the log, not a certainty. Check the lines above first.", "This is a rule match on the log text, not a certainty. Check the evidence before acting."],

  "security.agent": ["This app", "Agent"],
  "security.connected": ["Connected", "Connected"],
  "security.agent_note": ["This page is connected to it", "this dashboard is talking to it"],
  "security.https": ["Secure connection", "HTTPS"],
  "security.https_off": ["Off", "disabled"],
  "security.https_off_note": ["Only this PC can connect", "plain HTTP - loopback only"],
  "security.cert_loaded": ["On", "certificate loaded"],
  "security.issued_by": ["Issued by {issuer}", "Issued by {issuer}"],
  "security.unknown_issuer": ["an unknown issuer", "unknown issuer"],
  "security.cert_unreadable": ["Couldn't read the certificate", "the certificate could not be read"],
  "security.expiry": ["Certificate expires", "Certificate expiry"],
  "security.expiry_unreadable": ["Couldn't read", "could not be read from the certificate file"],
  "security.days_left": ["days left", "days remaining"],
  "security.tailscale": ["Tailscale", "Tailscale"],
  "security.ts_connected": ["Connected", "Connected"],
  "security.ts_disconnected": ["Not connected", "Not connected"],
  "security.auth": ["Sign-in", "Authentication"],
  "security.auth_on": ["Required", "enabled"],
  "security.auth_off": ["NOT SET", "NOT SET"],
  "security.auth_note": ["Sign-ins last {hours} hours", "sessions last {hours}h"],
  "security.failed": ["Failed sign-ins", "Failed sign-ins"],
  "security.failed_note": ["last 24 hours", "in the last 24 hours"],
  "security.covers": ["Certificate matches this address", "Certificate covers"],
  "security.covers_note": ["checked against {host}", "checked against {host}"],
  "security.covers_unset": ["No address set to check", "tls.hostname is not configured, so this cannot be checked"],
  "security.key_match": ["Key matches certificate", "Key matches certificate"],
  "security.key_note": ["The private key stays on the PC", "compared as public keys; the private key is never exposed"],
  "security.sessions": ["Signed in now ({count})", "Active sessions ({count})"],
  "security.col_user": ["User", "User"],
  "security.col_signed_in": ["Signed in", "Signed in"],
  "security.col_last_used": ["Last used", "Last used"],
  "security.col_from": ["From", "Source IP"],
  "security.col_device": ["Device", "Device"],
  "security.no_sessions": ["Nobody signed in", "No active sessions"],
  "security.rotate": ["New sign-in key", "Rotate my token"],
  "security.rotated": ["You have a new sign-in key", "This session's token was rotated"],
  "security.revoke": ["Sign everyone out", "Revoke all sessions"],
  "security.revoke_title": ["Sign everyone out?", "Sign every session out?"],
  "security.revoke_body": ["Everyone is signed out, you too.", "All sessions, including this one, are revoked. You will sign in again."],
  "security.audit": ["Who did what", "Audit log"],
  "security.col_when": ["When", "When"],
  "security.col_action": ["Action", "Action"],
  "security.col_target": ["Target", "Target"],
  "security.col_result": ["Result", "Result"],
  "security.audit_none": ["Nothing logged yet", "Nothing logged yet"],
  "security.result_ok": ["Done", "ok"],
  "security.bind": ["The app listens on {address}. Keep it on your Tailscale network only. Don't open it on your router.", "The agent is bound to {address}. Keep that address private to your tailnet; do not port-forward it."]
} /* end-strings-table */;

/* The display mode, set before first paint by theme.js from what this
   browser last used, then from the account's saved choice. */
export const display = {
  mode: document.documentElement.dataset.mode === "technical" ? "technical" : "simple",
};

export function technical() {
  return display.mode === "technical";
}

/* The text for key in the current mode, with {name} placeholders filled. */
export function t(key, values = null, mode = display.mode) {
  const entry = STRINGS[key];
  if (!entry) {
    // Shows up as a console error, which the browser check fails on.
    console.error(`Missing text: ${key}`);
    return key;
  }
  let text = entry[mode === "technical" ? 1 : 0];
  if (values) {
    text = text.replace(/\{(\w+)\}/g, (whole, name) =>
      (values[name] === undefined || values[name] === null ? whole : String(values[name])));
  }
  return text;
}

/* "1 player" / "3 players": key.one and key.other entries. */
export function tn(key, count, values = {}) {
  return t(`${key}.${count === 1 ? "one" : "other"}`, { count, ...values });
}
