/* Every piece of text the dashboard shows, in one table, each with a
   Simple version (everyday words, the default) and a Technical version
   (the precise terms: TPS, MSPT, RSS, -Xmx, TLS). Components look text up
   with t(key, values); nothing user-facing is written inline elsewhere.

   The table between the two markers is plain JSON, so tests can read it:
   tests/test_strings.py checks every entry has both versions with the same
   {placeholders}, and that every key the code uses exists. More languages
   can later live in their own files with this one as the fallback. */

export const STRINGS = /* strings-table */ {
  "app.name": ["Minecraft Server Control", "Minecraft Server Control"],

  "login.username": ["Username", "Username"],
  "login.password": ["Password", "Password"],
  "login.sign_in": ["Sign in", "Sign in"],
  "login.signing_in": ["Signing in…", "Signing in…"],

  "page.servers": ["All servers", "All servers"],
  "page.add_server": ["Add a server", "Add a server"],
  "page.overview": ["Overview", "Overview"],
  "page.players": ["Players", "Players"],
  "page.backups": ["Backups", "Backups"],
  "page.mods": ["Mods", "Mods"],
  "page.schedules": ["Schedules", "Schedules"],
  "page.performance": ["Performance", "Performance"],
  "page.console": ["Console", "Console"],
  "page.events": ["Events", "Events"],
  "page.crashes": ["Crashes", "Crashes"],
  "page.server_settings": ["Server settings", "Server settings"],
  "page.app_settings": ["Settings for this app", "Agent settings"],
  "page.security": ["Security", "Security"],

  "nav.server_pages": ["Pages for this server", "Pages for this server"],
  "nav.app_pages": ["Pages for this app", "Pages for this app"],
  "nav.group_live": ["Right now", "Live"],
  "nav.group_manage": ["Look after it", "Manage"],
  "nav.group_history": ["What happened", "History"],

  "tabs.label": ["Servers", "Servers"],
  "tabs.crashed": ["crashed", "crashed"],

  "state.online": ["Online", "Online"],
  "state.offline": ["Offline", "Offline"],
  "state.starting": ["Starting…", "Starting…"],
  "state.stopping": ["Stopping…", "Stopping…"],
  "state.restarting": ["Restarting…", "Restarting…"],
  "state.crashed": ["Crashed", "Crashed"],
  "state.unknown": ["Unknown", "Unknown"],

  "head.app": ["Settings", "Settings"],
  "head.players.one": ["{count} player online", "{count} player online"],
  "head.players.other": ["{count} players online", "{count} players online"],

  "action.start": ["Start", "Start"],
  "action.stop": ["Stop", "Stop"],
  "action.restart": ["Restart", "Restart"],
  "action.restart_now": ["Restart now", "Restart now"],
  "action.starting": ["Starting…", "Starting…"],
  "action.stopping": ["Stopping…", "Stopping…"],
  "action.restarting": ["Restarting…", "Restarting…"],
  "action.cancel": ["Cancel", "Cancel"],
  "action.cancelling": ["Cancelling…", "Cancelling…"],
  "action.confirm": ["Confirm", "Confirm"],
  "action.close": ["Close", "Close"],
  "action.save": ["Save", "Save"],
  "action.saving": ["Saving…", "Saving…"],
  "action.sign_out": ["Sign out", "Sign out"],
  "action.back_up_now": ["Back up now", "Back up now"],
  "action.view_details": ["View details", "View details"],
  "action.show_details": ["Show details", "Show raw details"],
  "action.what_happened": ["What happened?", "What happened?"],
  "action.restart_requested": ["Restart asked for. Watch the status to see it come back.", "Restart requested; not yet verified. Watch the status for ONLINE."],

  "confirm.stop_title": ["Stop the server?", "Stop the server?"],
  "confirm.stop_body": ["Players will be disconnected. The world is saved first.", "Players are disconnected. The server runs save-all and stop, then the process is waited for."],
  "confirm.restart_title": ["Restart the server?", "Restart the server?"],
  "confirm.restart_body": ["Players will be disconnected for a minute or two. The world is saved first.", "Players are disconnected. The server is stopped cleanly (save-all, stop) and started again."],

  "error.unreachable": ["Can't reach the server PC. Check it is on and connected.", "The agent did not answer. Check the PC is on and Tailscale is connected."],
  "error.session_ended": ["Your session ended. Please sign in again.", "Your session ended. Please sign in again."],
  "error.request_failed": ["Something went wrong (code {status}).", "Request failed (HTTP {status})."],

  "value.unknown": ["Unknown", "Unknown"],
  "value.yes": ["Yes", "Yes"],
  "value.no": ["No", "No"],

  "time.days_hours": ["{d}d {h}h", "{d}d {h}h"],
  "time.hours_minutes": ["{h}h {m}m", "{h}h {m}m"],
  "time.minutes": ["{m}m", "{m}m"],
  "time.seconds": ["{s}s", "{s}s"],
  "time.ago": ["{duration} ago", "{duration} ago"],
  "time.in": ["in {duration}", "in {duration}"],
  "time.never": ["Never", "Never"],

  "status.loading": ["Loading…", "Loading…"],

  "jobs.working": ["working", "working"],
  "jobs.running.one": ["{count} task running", "{count} job running"],
  "jobs.running.other": ["{count} tasks running", "{count} jobs running"],

  "live.connected": ["Live", "Live"],
  "live.reconnecting": ["Reconnecting…", "Reconnecting…"],
  "live.connected_title": ["Updates arrive as they happen.", "WebSocket connected: events arrive live."],
  "live.reconnecting_title": ["Lost touch with the server PC. Trying again.", "WebSocket disconnected; reconnecting with backoff."],
  "live.connected_announce": ["Live updates connected.", "Live updates connected."],
  "live.lost_announce": ["Live updates lost. Reconnecting.", "Live updates lost. Reconnecting."],
  "live.state_announce": ["Server is now {state}.", "Server is now {state}."],

  "event.server_started": ["The server started.", "The server started."],
  "event.server_stopped": ["The server stopped.", "The server stopped."],
  "event.server_crashed": ["The server crashed.", "The server crashed."],
  "event.server_crashed_code": ["The server crashed (code {code}).", "The server crashed (exit code {code})."],
  "event.crash_loop": ["The server keeps crashing, so automatic restarts are paused.", "Crash loop detected: automatic restarts are paused."],
  "event.server_recovered": ["The server is back online after a crash.", "The server is back online after a crash."],
  "event.other_crashed": ["{name} crashed.", "{name} crashed."],
  "event.other_crash_loop": ["{name} keeps crashing. Automatic restarts are paused.", "{name}: crash loop detected, automatic restarts paused."],
  "event.show_server": ["Show {name}", "Show {name}"],

  "hero.up_for": ["Up for {duration}", "Up {duration}"],
  "hero.version": ["Minecraft {mc}", "Minecraft {mc}"],
  "hero.version_loader": ["Minecraft {mc} with Fabric {loader}", "Minecraft {mc}, Fabric Loader {loader}"],
  "hero.so_far": ["({s} seconds so far)", "({s}s elapsed)"],
  "hero.stopping": ["Stopping. The world is being saved.", "Stopping. The world is being saved."],
  "hero.restarting": ["Restarting.", "Restarting."],
  "hero.crashed": ["The server crashed.", "The server crashed."],
  "hero.exit_code": ["Exit code {code}.", "Exit code {code}."],
  "hero.cause": ["Cause: {cause}.", "Cause: {cause}."],
  "hero.likely_cause": ["Probably because {cause}.", "Likely cause: {cause}."],
  "hero.possible_cause": ["Maybe because {cause}.", "Possible cause: {cause}."],
  "hero.cause_unknown": ["The cause isn't clear from the log.", "Cause not identified from the crash report or log."],
  "hero.reading_crash": ["Reading the crash log…", "Analysing the crash report…"],
  "hero.restart_paused": ["Automatic restarts are paused.", "Auto-restart is blocked."],
  "hero.restart_cancelled": ["The automatic restart was cancelled.", "Pending auto-restart was cancelled."],
  "hero.restarting_in": ["Restarting by itself in {s} seconds.", "Auto-restart in {s}s."],
  "hero.starting_now": ["Restarting now.", "Auto-restart firing now."],
  "hero.force_stopped": ["Stopped by force because it didn't stop in time.", "Force-killed after the stop timeout."],
  "hero.stopped": ["Stopped.", "Stopped."],
  "hero.not_running": ["Not running.", "Not running."],
  "hero.last_run": ["Last ran {versions}.", "Last run: {versions}."],
  "hero.unknown": ["The server's state isn't known yet.", "State UNKNOWN: no status reading yet."],

  "starting.java": ["Starting Java", "Starting the JVM"],
  "starting.mods": ["Loading mods", "Loading mods"],
  "starting.server": ["Starting the server", "Starting the Minecraft server"],
  "starting.world": ["Preparing the world", "Preparing spawn area"],

  "notice.maintenance": ["Maintenance mode is on.", "Maintenance mode is on."],
  "notice.maintenance_detail": ["Automatic restarts and scheduled tasks are paused.", "Auto-restart, crash recovery and scheduled tasks are suspended."],
  "notice.turn_off": ["Turn off", "Turn off"],
  "notice.turning_off": ["Turning off…", "Turning off…"],
  "notice.restart_paused": ["Automatic restarts are paused.", "Auto-restart is blocked."],
  "notice.restart_paused_detail": ["{reason}", "{reason}"],
  "notice.allow_restarts": ["Allow restarts again", "Clear the block"],
  "notice.allowing": ["Allowing…", "Allowing…"],
  "notice.restarts_allowed": ["Automatic restarts are allowed again.", "Auto-restart block cleared."],

  "overview.stats_label": ["Server at a glance", "Server at a glance"],
  "overview.players": ["Players", "Players"],
  "overview.of_max": ["of {max}", "of {max}"],
  "overview.players_waiting": ["Waiting for the first count", "Waiting for the first list reading"],
  "overview.speed": ["Server speed", "TPS"],
  "overview.speed_unit": ["of 20", "/ 20"],
  "overview.mspt_now": ["{ms} ms per tick", "{ms} ms per tick"],
  "overview.via": ["via {command}", "via {command}"],
  "overview.speed_detecting": ["Working out how to read speed…", "Detecting a TPS command…"],
  "overview.speed_unavailable": ["This server doesn't report its speed", "No TPS command works on this server"],
  "overview.speed_off": ["Speed readings are turned off", "TPS polling disabled"],
  "overview.speed_waiting": ["Waiting for the first reading", "Waiting for the first TPS reading"],
  "overview.when_running": ["Shown while the server runs", "Read while ONLINE"],
  "overview.memory": ["Memory used", "Server memory (RSS)"],
  "overview.of_limit": ["of {limit} allowed", "of {limit} -Xmx"],
  "overview.not_measured": ["Not measured yet", "No reading yet"],
  "overview.cpu": ["PC busyness", "PC CPU"],
  "overview.cpu_note": ["How hard the whole PC is working", "All processes, all cores"],
  "overview.last_backup": ["Last backup", "Last backup"],
  "overview.next_task": ["Next scheduled task", "Next scheduled job"],
  "overview.players_online": ["Players online", "Players online"],
  "overview.nobody_online": ["Nobody is online.", "Nobody is online."],
  "overview.players_unknown": ["Player list not known", "Player list not read"],
  "overview.players_unknown_hint": ["Shown once the server is running and answers.", "Read with the list command while ONLINE."],
  "overview.online_for": ["online {duration}", "online {duration}"],
  "overview.recommendations": ["Suggestions", "Recommendations"],
  "overview.details": ["Details", "Details"],
  "overview.minecraft": ["Minecraft", "Minecraft"],
  "overview.loader": ["Fabric Loader", "Fabric Loader"],
  "overview.java": ["Java", "Java"],
  "overview.port": ["Port", "Port"],
  "overview.mods": ["Mods", "Mods"],
  "overview.disk_free": ["Free disk space", "Disk free"],
  "overview.detected_on_start": ["Found when the server starts", "Detected on next start"],
  "overview.recent_console": ["Recent console output", "Recent console output"],
  "overview.open_console": ["Open the console", "Open the console"],

  "summary.last_hour": ["Last hour:", "Last hour:"],
  "summary.speed": ["about {avg} on average, lowest {low}", "avg {avg} TPS, min {low}"],
  "summary.samples": ["{n} readings", "{n} samples"],
  "summary.not_yet": ["No readings in the last hour yet.", "No samples in the last hour."],
  "summary.memory_trend": ["went from {from} to {to}", "{from} → {to}"],
  "summary.memory_peak": ["highest {peak}", "peak {peak}"],
  "summary.limit": ["{limit} allowed", "limit {limit} (-Xmx)"],
  "summary.no_limit": ["No memory limit is set.", "No -Xmx set."],
  "summary.cpu": ["about {avg}% on average, highest {high}%", "avg {avg}%, max {high}%"],
  "summary.players_unknown": ["Player list not known yet.", "Player list not read yet."],
  "summary.nobody": ["Nobody is online.", "Nobody is online."],

  "backup.never": ["No backups yet", "No backups yet"],
  "backup.never_hint": ["Back up now so you can undo a broken world later.", "No backup exists for this server."],
  "backup.checked": ["Checked", "Verified"],
  "backup.unchecked": ["Not checked", "Unverified"],
  "backup.failed": ["Failed", "Failed"],
  "backup.working": ["Backing up…", "Backing up…"],
  "backup.done": ["Backup saved: {name}", "Backup created and verified: {name}"],

  "schedule.nothing": ["Nothing scheduled", "Nothing scheduled"],
  "schedule.add": ["Add a schedule", "Add a schedule"],
  "schedule.next": ["{task} {when}", "{task} {when}"],
  "schedule.open": ["See all schedules", "See all schedules"],

  "task.start": ["Start the server", "Start the server"],
  "task.stop": ["Stop the server", "Stop the server"],
  "task.restart": ["Restart the server", "Restart the server"],
  "task.backup": ["Back up", "Back up"],
  "task.log_cleanup": ["Clean up old logs", "Log cleanup"],
  "task.notify": ["Send a message", "Notify"],
  "task.maintenance_on": ["Turn on maintenance mode", "Turn on maintenance mode"],
  "task.maintenance_off": ["Turn off maintenance mode", "Turn off maintenance mode"],

  "rec.none": ["Nothing to suggest right now.", "No recommendations fire right now."],
  "rec.snooze": ["Not now", "Not now"],
  "rec.snooze_title": ["Hide until something changes", "Snooze until the evidence changes"],
  "rec.dismiss": ["Don't show again", "Don't show again"],
  "rec.dismiss_title": ["Never show this suggestion for this server", "Dismiss permanently for this server"],
  "rec.show_again": ["Show again", "Show again"],
  "rec.hidden.one": ["{count} hidden suggestion", "{count} hidden recommendation"],
  "rec.hidden.other": ["{count} hidden suggestions", "{count} hidden recommendations"],

  "cause.OutOfMemoryError": ["the server ran out of memory", "OutOfMemoryError: the Java heap ran out"],
  "cause.JavaHeapError": ["Java could not get the memory it was set to use", "the JVM could not reserve the -Xmx heap"],
  "cause.JavaVersionIncompatible": ["the installed Java doesn't match this Minecraft version", "the Java version is incompatible with this Minecraft version"],
  "cause.ModDependencyError": ["a mod is missing something it needs, or has the wrong version of it", "a mod dependency is missing or out of range"],
  "cause.MissingMod": ["a required mod is not installed", "a required mod is not installed"],
  "cause.IncompatibleMod": ["two installed mods don't work together", "two installed mods don't work together"],
  "cause.MixinError": ["a mod failed to apply its changes to the game", "a mixin failed to apply"],
  "cause.FabricLoaderError": ["Fabric Loader refused to start", "Fabric Loader refused to start"],
  "cause.ClassNotFoundException": ["a mod was made for a different game version", "ClassNotFoundException: a mod targets another game version"],
  "cause.NoSuchMethodError": ["installed mods don't match each other's versions", "NoSuchMethodError: mismatched mod versions"],
  "cause.WorldChunkError": ["world data could not be loaded or saved", "chunk or region data could not be read or written"],
  "cause.DiskStorageError": ["the disk is full or can't be written to", "the disk is full or can't be written to"],
  "cause.PortInUse": ["another program is already using the server's port", "the server port is already bound"],
  "cause.EulaNotAccepted": ["the Minecraft EULA has not been accepted", "the Minecraft EULA has not been accepted"],
  "cause.NetworkError": ["a network error", "a network error"],
  "cause.ServerThreadCrash": ["an error in the game's main loop", "an exception on the main server thread"],

  "servers.none": ["No servers yet", "No servers yet"],
  "servers.none_hint": ["Use the + tab to add the folder of a Minecraft server.", "Add one with the + tab or in config.yaml."],
  "servers.players": ["Players", "Players"],
  "servers.players_of": ["{n} of {max}", "{n} of {max}"],
  "servers.uptime": ["Running for", "Uptime"],
  "servers.not_running": ["Not running", "Not running"],
  "servers.port": ["Port", "Port"],

  "add.existing": ["Add a server that's already on this PC", "Add a server that's already on this PC"],
  "add.existing_hint": ["Pick the folder that has the server's .jar file and world in it.", "The server directory: holds the server jar, server.properties and the world."],
  "add.name": ["Name", "Name"],
  "add.folder": ["Folder", "Server directory"],
  "add.more_options": ["More options", "Advanced"],
  "add.jar": ["Server file", "Server jar"],
  "add.jar_hint": ["Leave empty to find it by itself.", "Leave empty to auto-detect the jar in the directory."],
  "add.submit": ["Add server", "Add server"],
  "add.adding": ["Adding…", "Adding…"],
  "add.need_name_and_folder": ["Give the server a name and a folder.", "Give the server a name and a folder."],
  "add.added": ["{name} added.", "{name} added."],
  "add.color_used": ["{color} (already used)", "{color} (already used)"],

  "color.blue": ["Blue", "Blue"],
  "color.orange": ["Orange", "Orange"],
  "color.green": ["Green", "Green"],
  "color.crimson": ["Crimson", "Crimson"],
  "color.violet": ["Violet", "Violet"],
  "color.amber": ["Amber", "Amber"],
  "color.teal": ["Teal", "Teal"],
  "color.magenta": ["Magenta", "Magenta"],
  "color.cyan": ["Cyan", "Cyan"],
  "color.olive": ["Olive", "Olive"],
  "color.rose": ["Rose", "Rose"],
  "color.indigo": ["Indigo", "Indigo"],

  "theme.system": ["Match my device", "System"],
  "theme.light": ["Light", "Light"],
  "theme.dark": ["Dark", "Dark"],
  "theme.graphite": ["Graphite", "Graphite"],
  "theme.contrast": ["High contrast", "High contrast"],

  "mode.simple": ["Simple", "Simple"],
  "mode.simple_hint": ["Everyday words. Details stay tucked away until you open them.", "Everyday words. Details stay tucked away until you open them."],
  "mode.technical": ["Technical", "Technical"],
  "mode.technical_hint": ["Exact terms (TPS, MSPT, -Xmx), more numbers, and advanced sections open.", "Exact terms (TPS, MSPT, -Xmx), more numbers, and advanced sections open."],

  "appset.appearance": ["Appearance", "Appearance"],
  "appset.theme": ["Theme", "Theme"],
  "appset.detail": ["How much detail", "Display mode"],
  "appset.mode": ["How much detail", "Display mode"],
  "appset.alerts": ["Alerts", "Alerts"],
  "appset.discord": ["Discord", "Discord"],
  "appset.email": ["Email", "Email"],
  "appset.discord_missing": ["Add the Discord link to the .env file on the PC first.", "Set DISCORD_WEBHOOK_URL in .env first."],
  "appset.email_missing": ["Add the email account details to the .env file on the PC first.", "Set the SMTP_* values in .env first."],
  "appset.send_test": ["Send a test", "Send a test"],
  "appset.sending": ["Sending…", "Sending…"],
  "appset.test_sent": ["Test sent.", "Test sent."],
  "appset.test_failed": ["The test didn't go through. Check the details in .env.", "Test failed. Check the .env settings and the agent log."],
  "appset.alert_details": ["When to alert", "Thresholds and events"],
  "appset.cpu_alert": ["Alert when the PC is this busy (%)", "CPU alert threshold (%)"],
  "appset.ram_alert": ["Alert when the PC's memory is this full (%)", "RAM alert threshold (%)"],
  "appset.disk_alert": ["Alert when free disk space falls below (GB)", "Disk free threshold (GB)"],
  "appset.tps_alert": ["Alert when server speed falls below (of 20)", "TPS minimum"],
  "appset.mspt_alert": ["Alert when each tick takes longer than (ms)", "MSPT maximum (ms)"],
  "appset.repeat_alert": ["Wait at least this long between the same alert (seconds)", "Minimum interval between repeats (s)"],
  "appset.which_events": ["Alert me about", "Events"],
  "appset.save_alerts": ["Save alert settings", "Save alert settings"],
  "appset.secrets_note": ["Links and passwords live in the .env file on the PC, never in the dashboard.", "Secrets (webhook URL, SMTP password) are read from .env only and never sent to the browser."],
  "appset.maintenance": ["Maintenance mode", "Maintenance mode"],
  "appset.maintenance_label": ["Pause automatic restarts and schedules for every server", "Suspend auto-restart and schedules (all servers)"],
  "appset.maintenance_on": ["Maintenance mode is on.", "Maintenance mode is on."],
  "appset.maintenance_off": ["Maintenance mode is off.", "Maintenance mode is off."],
  "appset.startup": ["Starting with Windows", "Windows startup task"],
  "appset.startup_hint": ["Checks whether this app starts by itself when the PC turns on. It only looks; it changes nothing.", "Inspects the scheduled task (read-only)."],
  "appset.startup_check": ["Check now", "Inspect"],
  "appset.startup_asking": ["Checking…", "Inspecting…"],
  "appset.check": ["Check", "Check"],
  "appset.result": ["Result", "Result"],

  "settings.saved": ["Settings saved.", "Settings saved."],
  "settings.nothing_changed": ["Nothing changed.", "Nothing changed."],

  "alert_event.server_started": ["The server started", "The server started"],
  "alert_event.server_stopped": ["The server stopped", "The server stopped"],
  "alert_event.server_crashed": ["The server crashed", "The server crashed"],
  "alert_event.server_restarted": ["The server restarted", "The server restarted"],
  "alert_event.server_recovered": ["The server came back after a crash", "The server came back after a crash"],
  "alert_event.player_joined": ["A player joined", "A player joined"],
  "alert_event.player_left": ["A player left", "A player left"],
  "alert_event.high_ram": ["The PC's memory is nearly full", "High RAM"],
  "alert_event.high_cpu": ["The PC is very busy", "High CPU"],
  "alert_event.low_disk": ["Disk space is low", "Low disk"],
  "alert_event.low_tps": ["The server is running slowly", "Low TPS"],
  "alert_event.high_mspt": ["Ticks are taking too long", "High MSPT"],
  "alert_event.backup_completed": ["A backup finished", "A backup finished"],
  "alert_event.backup_failed": ["A backup failed", "A backup failed"],
  "alert_event.mod_installed": ["A mod was installed", "A mod was installed"],
  "alert_event.mod_removed": ["A mod was removed", "A mod was removed"],
  "alert_event.mod_updated": ["A mod was updated", "A mod was updated"],
  "alert_event.mod_dependency_problem": ["A mod is missing something it needs", "Mod dependency problem"],
  "alert_event.auth_failure": ["Someone failed to sign in", "Authentication failure"],
  "alert_event.maintenance_mode": ["Maintenance mode turned on or off", "Maintenance mode turned on or off"],
  "alert_event.certificate_expiring": ["The HTTPS certificate is about to run out", "TLS certificate expiring"],
  "alert_event.servers_changed": ["A server was added or removed", "A server was added or removed"],
  "alert_event.cpu_cores_failed": ["A server's CPU core choice couldn't be applied", "CPU affinity could not be applied"],

  "startup.registered_correctly": ["Starts with Windows, set up correctly", "Registered correctly"],
  "startup.not_registered": ["Doesn't start with Windows", "Not registered"],
  "startup.problems_found": ["Set to start with Windows, but something is wrong", "Problems found"],
  "startup.unsupported": ["Only available on Windows", "Unsupported (not Windows)"],
  "startup.registered": ["Startup entry", "Task registered"],
  "startup.found": ["Found", "Found"],
  "startup.not_found": ["Not found", "Not found"],
  "startup.mode": ["Starts when", "Trigger"],
  "startup.at_boot": ["The PC turns on", "At boot"],
  "startup.at_logon": ["You sign in to Windows", "At logon"],
  "startup.points_here": ["Points to this copy of the app", "Points to the current install"],
  "startup.last_run": ["Last ran", "Last run time"],
  "startup.last_start": ["Last start", "Last recorded startup"],
  "startup.last_start_value": ["{when} ({by})", "{when} ({by})"],
  "startup.none": ["None recorded", "None recorded"],
  "startup.initialised": ["Started fully", "Controller initialised"],
  "startup.mechanism": ["Mechanism", "Mechanism"],
  "startup.command": ["Command", "Command"],
  "startup.folder": ["Folder", "Working directory"],
  "startup.last_result": ["Last result", "Last result"],

  "serverset.identity": ["Name and color", "Name and color"],
  "serverset.name": ["Name", "Name"],
  "serverset.color": ["Color", "Color"],
  "serverset.custom_color": ["Pick any color", "Custom color"],
  "serverset.save_identity": ["Save name and color", "Save name and color"],
  "serverset.folder": ["Folder: {folder}", "Directory: {folder}"],
  "serverset.crashes": ["When it crashes", "Crash recovery"],
  "serverset.auto_restart": ["Restart by itself after a crash", "Auto-restart after a crash"],
  "serverset.crash_details": ["More crash options", "Advanced"],
  "serverset.restart_delay": ["Wait before restarting (seconds)", "Restart delay (s)"],
  "serverset.max_crashes": ["Give up after this many crashes", "Max crashes in window"],
  "serverset.max_crashes_hint": ["…within {minutes} minutes. Then automatic restarts pause until you allow them.", "Within {minutes} min; then auto-restart is blocked until cleared."],
  "serverset.memory": ["Memory", "Memory"],
  "serverset.memory_limit": ["Memory the server may use (GB)", "Max heap -Xmx (GB)"],
  "serverset.memory_hint": ["More isn't always better: leave enough for Windows and other programs.", "Sets -Xmx in the JVM arguments. Applies on next start."],
  "serverset.memory_unset": ["No limit set yet. Java picks one by itself.", "No -Xmx set: the JVM default applies."],
  "serverset.launch_args": ["Java start-up options", "JVM arguments"],
  "serverset.jvm_args": ["Java options", "JVM arguments"],
  "serverset.jvm_args_hint": ["One line, as Java expects it. Applies the next time the server starts.", "Space-separated. Applies on next start."],
  "serverset.cpu": ["CPU cores", "CPU affinity"],
  "serverset.cpu_unreadable": ["This PC's cores couldn't be read.", "Logical core count unavailable."],
  "serverset.all_cores": ["Use every core ({count})", "All logical cores ({count})"],
  "serverset.core": ["Core {n}", "Core {n}"],
  "serverset.core_shared": ["also used by {names}", "shared with {names}"],
  "serverset.cores_now": ["Right now it's using {cores}.", "Applied affinity: {cores}."],
  "serverset.cores_unknown": ["Which cores it uses right now isn't known: {reason}", "Applied affinity unknown: {reason}"],
  "serverset.every_core": ["every core", "all cores"],
  "serverset.half_cores": ["Pick half", "Select half"],
  "serverset.pick_a_core": ["Pick at least one core.", "Pick at least one core."],
  "serverset.cores_applied": ["Saved and applied.", "Saved and applied to the running process."],
  "serverset.cores_next_start": ["Saved. Used from the next start.", "Saved; applied on next start."],
  "serverset.cores_not_applied": ["Saved, but couldn't apply it now: {reason}", "Saved; live apply failed: {reason}"],
  "serverset.backups": ["Backups", "Backups"],
  "serverset.keep_daily": ["Daily backups to keep", "keep_daily"],
  "serverset.keep_weekly": ["Weekly backups to keep", "keep_weekly"],
  "serverset.keep_monthly": ["Monthly backups to keep", "keep_monthly"],
  "serverset.timing": ["Start and stop timing", "Timeouts"],
  "serverset.start_timeout": ["Give up starting after (seconds)", "Start timeout (s)"],
  "serverset.stop_timeout": ["Force it to stop after (seconds)", "Stop timeout (s)"],
  "serverset.stop_timeout_hint": ["If the server hasn't stopped by then, it is stopped by force.", "After this the process is killed."],
  "serverset.remove": ["Remove from this list", "Remove server"],
  "serverset.remove_hint": ["Removes the server from the dashboard. Its folder, world and backups stay on the PC.", "Unregisters the server. Files, worlds and backups are not touched."],
  "serverset.remove_last": ["This is the only server, so it can't be removed.", "The last server cannot be removed."],
  "serverset.remove_button": ["Remove from list", "Remove"],
  "serverset.remove_title": ["Remove {name}?", "Remove {name}?"],
  "serverset.remove_body": ["It disappears from the dashboard. Nothing is deleted from the PC.", "Unregisters the server; no files are deleted."],
  "serverset.remove_confirm": ["Remove", "Remove"],
  "serverset.removed": ["{name} removed from the list.", "{name} removed from the list."],

  "perf.range": ["Time shown", "Time shown"],
  "perf.range_1": ["1 hour", "1h"],
  "perf.range_6": ["6 hours", "6h"],
  "perf.range_24": ["1 day", "24h"],
  "perf.range_168": ["1 week", "7d"],
  "perf.pc_cpu": ["PC busyness", "PC CPU"],
  "perf.pc_cpu_note": ["Everything running on the PC", "All processes"],
  "perf.server_cpu": ["Server's share", "Server CPU"],
  "perf.server_cpu_note": ["How much of the PC the server uses", "Java process, % of all cores"],
  "perf.server_cpu_all": ["Can use every core", "Affinity: all cores"],
  "perf.server_cpu_some": ["Limited to {n} of {total} cores", "Affinity: {n} of {total} cores"],
  "perf.server_memory": ["Server memory", "Server memory (RSS)"],
  "perf.of_limit": ["of {limit} allowed", "of {limit} -Xmx"],
  "perf.not_running_note": ["Measured while running", "Read while running"],
  "perf.pc_memory": ["PC memory", "PC RAM"],
  "perf.pc_memory_note": ["All programs together", "All processes"],
  "perf.disk_free": ["Free disk space", "Disk free"],
  "perf.on_server_drive": ["On the server's drive", "Server volume"],
  "perf.unknown_because": ["Unknown: {reason}", "Unknown: {reason}"],
  "perf.chart_cpu": ["PC busyness", "CPU"],
  "perf.chart_memory": ["Server memory", "Server memory (RSS)"],
  "perf.chart_speed": ["Server speed", "TPS"],
  "perf.chart_players": ["Players", "Players"],
  "perf.chart_mspt": ["Time per tick", "MSPT"],
  "perf.chart_pc_memory": ["PC memory", "PC RAM used"],
  "perf.speed_unit": ["of 20", "ticks/s"],
  "perf.players_unit": ["players", "players"],
  "perf.limit": ["Limit {limit}", "-Xmx {limit}"],
  "perf.mspt_budget": ["50 ms: the most a tick can take", "50 ms budget"],
  "perf.memory_empty": ["Shown while the server runs.", "No samples: the server was not running."],
  "perf.speed_empty": ["No speed readings in this time.", "No TPS samples in this range."],
  "perf.players_empty": ["No player counts in this time.", "No player samples in this range."],
  "perf.storage": ["Disk space used", "Storage"],
  "perf.storage_what": ["What", "What"],
  "perf.storage_size": ["Size", "Size"],
  "perf.storage_worlds": ["Worlds", "Worlds"],
  "perf.storage_backups": ["Backups", "Backups"],
  "perf.storage_mods": ["Mods", "Mods"],
  "perf.storage_logs": ["Logs", "Logs"],
  "perf.storage_other": ["Other", "Other"],
  "perf.storage_free": ["Free on the drive", "Free on volume"],
  "perf.network": ["Network", "Network"],
  "perf.net_in": ["Coming in", "Received"],
  "perf.net_out": ["Going out", "Sent"],
  "perf.speed_readings": ["How speed is read", "TPS source"],
  "perf.health": ["Health checks", "Health checks"],

  "health.all_ok": ["Everything checked out", "ALL CHECKS VERIFIED"],
  "health.partial": ["Some things couldn't be checked", "PARTIALLY VERIFIED"],
  "health.attention": ["Something needs attention", "ATTENTION NEEDED"],
  "health.limit": ["limit {limit}", "limit {limit}"],

  "chart.no_samples": ["Nothing measured in this time.", "No samples in this range."],
  "chart.aria": ["{title}: latest {latest}, lowest {low}, highest {high}. Use the arrow keys to read each point.", "{title}: latest {latest}, lowest {low}, highest {high}. Use the arrow keys to read each point."],

  "tps.load_failed": ["Couldn't read the speed settings: {error}", "TPS status unavailable: {error}"],
  "tps.status": ["Status", "Status"],
  "tps.command": ["Command", "Command"],
  "tps.detection": ["Chosen", "Detection"],
  "tps.last_reading": ["Last reading", "Last reading"],
  "tps.none_yet": ["None yet", "None yet"],
  "tps.none": ["None", "None"],
  "tps.manual": ["Chosen by you", "Manual"],
  "tps.off": ["Off", "Disabled"],
  "tps.auto": ["Found by itself", "Auto-detected"],
  "tps.auto_remembered": ["Found by itself earlier", "Auto (remembered)"],
  "tps.manual_silent": ["None: readings are off", "None (polling off)"],
  "tps.state_active": ["Working", "Active"],
  "tps.state_detecting": ["Finding out…", "Detecting…"],
  "tps.state_unavailable": ["Not available", "Unavailable"],
  "tps.state_disabled": ["Off", "Disabled"],
  "tps.state_idle": ["Waiting for the server", "Idle"],
  "tps.configure": ["Choose how", "Configure"],
  "tps.change": ["Change", "Change command"],
  "tps.detect_again": ["Find again", "Re-detect"],
  "tps.detecting": ["Finding…", "Detecting…"],
  "tps.needs_online": ["The server must be running", "Requires ONLINE"],
  "tps.dialog_title": ["How to read server speed", "TPS command"],
  "tps.dialog_body": ["Minecraft doesn't report its speed by itself. Pick how to ask it, or let the app work it out.", "Command sent through the console to read TPS. Auto tries the known ones in order."],
  "tps.opt_auto": ["Work it out by itself", "Auto-detect"],
  "tps.opt_tick": ["Built-in (Minecraft 1.20.3 and newer)", "tick query (vanilla 1.20.3+)"],
  "tps.opt_carpet": ["Carpet mod", "tps (Carpet)"],
  "tps.opt_spark": ["Spark mod", "spark tps"],
  "tps.opt_custom": ["Something else…", "Custom…"],
  "tps.opt_off": ["Don't read speed", "Off"],
  "tps.custom_placeholder": ["command", "command"],
  "tps.custom_label": ["Your command", "Custom command"],
  "tps.saved_auto": ["It will work out how by itself.", "Set to auto-detect."],
  "tps.saved_off": ["Speed readings turned off.", "TPS polling disabled."],
  "tps.saved_command": ["Speed will be read with {command}.", "TPS command set: {command}"],

  "console.empty": ["Nothing here yet", "No output yet"],
  "console.empty_hint": ["Messages from the server show up here while it runs.", "Server stdout appears here while running."],
  "console.no_match": ["Nothing matches", "Nothing matches"],
  "console.no_match_hint": ["No lines contain “{filter}”.", "No lines contain “{filter}”."],
  "console.filter": ["Filter", "Filter"],
  "console.filter_label": ["Show only lines containing", "Filter lines"],
  "console.follow": ["Follow", "Auto-scroll"],
  "console.follow_title": ["Keep showing the newest lines", "Scroll to new output"],
  "console.pause": ["Pause", "Pause"],
  "console.pause_title": ["Stop new lines from appearing for now", "Freeze the view; output keeps buffering"],
  "console.toggle_on": ["{label} on", "{label} on"],
  "console.toggle_off": ["{label} off", "{label} off"],
  "console.copy": ["Copy", "Copy"],
  "console.copy_title": ["Copy the lines shown", "Copy visible lines"],
  "console.copied": ["Copied.", "Copied."],
  "console.copy_unavailable": ["This browser didn't allow copying.", "Clipboard unavailable."],
  "console.download": ["Download", "Download"],
  "console.download_title": ["Save the lines shown as a file", "Download visible lines as .log"],
  "console.clear": ["Clear", "Clear"],
  "console.clear_title": ["Clear this view (the log file stays)", "Clear the buffer; latest.log is untouched"],
  "console.clearing": ["Clearing…", "Clearing…"],
  "console.cleared": ["Console cleared.", "Console cleared."],
  "console.output_label": ["Server console output", "Server console output"],
  "console.command_placeholder": ["Type a command, like say hello", "Command (without /)"],
  "console.command_label": ["Command to send", "Command to send"],
  "console.send": ["Send", "Send"],
  "console.sending": ["Sending…", "Sending…"],
  "console.run_title": ["Run {command}?", "Run {command}?"],
  "console.run": ["Run", "Run"],
  "console.hint": ["Commands go to the Minecraft server only, never to Windows. Ones that affect players ask first.", "Sent to the server's console only, never to Windows. Commands that affect players ask for confirmation."],
  "console.load_more": ["Show older lines", "Load more"],

  "mods.running_notice": ["The server is {state}. Stop it to add, update or remove mods.", "Server is {state}: mod changes need it stopped."],
  "mods.stop_first": ["Stop the server before changing mods.", "Stop the server before changing mods."],
  "mods.stop_first_short": ["Stop the server first", "Stop the server first"],
  "mods.status_ok": ["Working", "OK"],
  "mods.status_warn": ["Check", "Warning"],
  "mods.status_error": ["Problem", "Problem"],
  "mods.status_off": ["Turned off", "Disabled"],
  "mods.col_mod": ["Mod", "Mod"],
  "mods.col_version": ["Version", "Version"],
  "mods.col_minecraft": ["Minecraft", "Minecraft"],
  "mods.col_status": ["Status", "Status"],
  "mods.col_downloads": ["Downloads", "Downloads"],
  "mods.col_when": ["When", "When"],
  "mods.col_who": ["Who", "Who"],
  "mods.col_action": ["Action", "Action"],
  "mods.col_change": ["Change", "Change"],
  "mods.col_result": ["Result", "Result"],
  "mods.col_saved": ["Saved", "Saved"],
  "mods.update_to": ["Update available: {version}", "Update: {version}"],
  "mods.update": ["Update", "Update"],
  "mods.turn_off": ["Turn off", "Disable"],
  "mods.turn_on": ["Turn on", "Enable"],
  "mods.turned_off": ["{name} turned off.", "{name} disabled."],
  "mods.turned_on": ["{name} turned on.", "{name} enabled."],
  "mods.history": ["Versions", "Versions"],
  "mods.remove": ["Remove", "Remove"],
  "mods.none": ["No mods installed", "No mods installed"],
  "mods.none_hint": ["Search below to add some.", "Search Modrinth below, or put .jar files in the mods folder."],
  "mods.add": ["Add mods", "Add mods"],
  "mods.search": ["Search", "Search"],
  "mods.searching": ["Searching…", "Searching…"],
  "mods.search_placeholder": ["Search for a mod", "Search Modrinth"],
  "mods.search_label": ["Search for mods", "Search Modrinth"],
  "mods.search_hint": ["Only mods for Minecraft {version} on Fabric are shown.", "Results are filtered to Fabric, game version {version}."],
  "mods.nothing_found": ["Nothing found.", "Nothing found."],
  "mods.install": ["Install", "Install"],
  "mods.about_checks": ["How mods are checked", "About the checks"],
  "mods.limits": ["Limits: {limits}", "Limitations: {limits}"],
  "mods.change_history": ["What changed", "Change history"],
  "mods.no_history": ["No changes yet.", "No history."],
  "mods.no_build": ["There's no version of this mod for this server.", "No compatible version found."],
  "mods.install_title": ["Install this mod?", "Install this mod?"],
  "mods.install_what": ["{name} {version}", "{name} {version}"],
  "mods.install_size": ["Size: {size}", "Size: {size}"],
  "mods.install_minecraft": ["For Minecraft {versions}", "Game versions: {versions}"],
  "mods.install_file": ["File: {file}", "File: {file}"],
  "mods.install_side": ["Server side: {side}", "Server side: {side}"],
  "mods.install_licence": ["Licence: {licence}", "Licence: {licence}"],
  "mods.install_checked": ["The download is checked before it's used.", "The SHA-512 from Modrinth is verified before the file is placed."],
  "mods.install_confirm": ["Install", "Install"],
  "mods.installed_toast": ["{name} {version} installed. It's loaded the next time the server starts.", "Installed {name} {version}. Loaded by Minecraft: not verified until the server starts."],
  "mods.deps_missing": ["This mod needs others that aren't installed. See the list at the top.", "Required dependencies are still missing."],
  "mods.update_title": ["Update {name}?", "Update {name}?"],
  "mods.update_archived": ["The old version is kept, so you can go back.", "The current file is archived and can be rolled back."],
  "mods.updated_toast": ["Updated to {version}. Used from the next start.", "Updated to {version}; loaded on next start."],
  "mods.remove_title": ["Remove {name}?", "Remove {name}?"],
  "mods.needed_by": ["{name} needs it ({requires})", "{name} requires it ({requires})"],
  "mods.not_needed": ["No other mod needs it.", "No installed mod depends on it."],
  "mods.remove_kept": ["A copy is kept, so you can put it back.", "The file is archived, not deleted."],
  "mods.removed_toast": ["{name} removed.", "{name} removed."],
  "mods.versions_title": ["Versions of {name}", "Archived versions: {name}"],
  "mods.current": ["In use", "Current"],
  "mods.file_missing": ["File missing", "File missing"],
  "mods.rollback": ["Go back to this", "Roll back"],
  "mods.rollback_title": ["Go back to {version}?", "Roll back to {version}?"],
  "mods.rollback_body": ["The version in use now is kept too.", "The current file is archived first."],
  "mods.rolled_back": ["Back on {version}.", "Rolled back to {version}."],
  "mods.no_versions": ["No saved versions.", "No archived versions."],
  "mods.installed.one": ["{count} mod installed", "{count} mod installed"],
  "mods.installed.other": ["{count} mods installed", "{count} mods installed"],
  "mods.problems.one": ["{count} problem with the mods", "{count} mod problem"],
  "mods.problems.other": ["{count} problems with the mods", "{count} mod problems"],
  "mods.install_deps.one": ["Also install the {count} mod it needs", "Also install {count} required dependency"],
  "mods.install_deps.other": ["Also install the {count} mods it needs", "Also install {count} required dependencies"],

  "deps.checking": ["Checking what mods need…", "Resolving dependencies…"],
  "deps.check_failed": ["Couldn't check what mods need.", "Dependency check failed."],
  "deps.two_names": ["{a} and {b}", "{a} and {b}"],
  "deps.many_names": ["{a}, {b} and {n} more", "{a}, {b} and {n} more"],
  "deps.status_missing": ["Missing", "Missing"],
  "deps.status_incompatible": ["Wrong version", "Wrong version"],
  "deps.status_disabled": ["Turned off", "Disabled"],
  "deps.status_platform_incompatible": ["Won't work here", "Incompatible"],
  "deps.status_unverified": ["Not checked", "Not checked"],
  "deps.status_satisfied": ["Installed", "Installed"],
  "deps.status_platform_ok": ["OK", "OK"],
  "deps.optional": ["Optional", "Optional"],
  "deps.required_by": ["Needed by {names}.", "Required by {names}."],
  "deps.recommended_by": ["Suggested by {names}.", "Recommended by {names}."],
  "deps.version": ["Version: {range}.", "Range: {range}."],
  "deps.installed_version": ["Installed: {version}.", "Installed: {version}."],
  "deps.not_on_modrinth": ["Not found on Modrinth. It may need to be added by hand.", "Not on Modrinth; install manually."],
  "deps.view_on_modrinth": ["View on Modrinth", "View on Modrinth"],
  "deps.all_ok": ["Every mod has what it needs.", "All declared dependencies are installed."],
  "deps.problems": ["Some mods are missing what they need", "Dependency problems"],
  "deps.install_missing": ["Install what's missing ({n})", "Install missing dependencies ({n})"],
  "deps.title": ["What mods need", "Dependencies"],
  "deps.optional_title": ["Optional extras ({n})", "Optional dependencies ({n})"],
  "deps.optional_hint": ["Mods work without these, but may do more with them.", "Not required; some features may depend on them."],
  "deps.plan_intro": ["These will be downloaded from Modrinth and checked before use:", "Downloaded from Modrinth and verified against published hashes:"],
  "deps.needed_by": ["Needed by {names}.", "Required by {names}."],
  "deps.range_unchecked": ["Couldn't confirm this version fits.", "Range not verifiable against this version."],
  "deps.nothing_automatic": ["Nothing can be downloaded by itself.", "Nothing resolvable automatically."],
  "deps.not_automatic": ["Not installed by itself:", "Not resolvable automatically:"],
  "deps.already_installed": ["Already installed: {names}.", "Already installed: {names}."],
  "deps.plan_safety": ["Mods you have aren't replaced. Each download is kept so it can be undone.", "Existing mods are not replaced. Each download is archived and can be rolled back."],
  "deps.planning": ["Checking…", "Checking…"],
  "deps.installing": ["Installing…", "Installing…"],
  "deps.plan_failed": ["Couldn't plan the install. {error}", "Planning failed: {error}"],
  "deps.nothing_title": ["Nothing to install by itself", "Nothing to install automatically"],
  "deps.install_confirm": ["Install {n}", "Install {n}"],
  "deps.installed_toast": ["Installed {names}. They're loaded the next time the server starts.", "Installed {names}. Loaded by Minecraft: not verified until the server starts."],
  "deps.failed_toast": ["{name} couldn't be installed. {error}", "{name} failed: {error}"],
  "deps.still_missing": ["Still missing: {names}.", "Still missing: {names}."],
  "deps.install_failed": ["Couldn't install them. {error}", "Install failed: {error}"],
  "deps.missing.one": ["{count} needed mod is missing", "{count} missing dependency"],
  "deps.missing.other": ["{count} needed mods are missing", "{count} missing dependencies"],
  "deps.install_title.one": ["Install {count} mod?", "Install {count} mod?"],
  "deps.install_title.other": ["Install {count} mods?", "Install {count} mods?"],

  "backups.last_change": ["Last change", "Last change"],
  "backups.last_change_body": ["{title}, {when}. Undo puts back the copy {backup} made just before it.", "{title}, {when}. Undo restores the safety copy {backup} taken just before it."],
  "backups.undo_change": ["Undo this change", "Undo this change"],
  "backups.started": ["Backing up. Big worlds take a while.", "Backup started. Large worlds take a while."],
  "backups.verified_toast": ["Backup saved and checked: {name} ({entries} files)", "Backup verified: {name} ({entries} entries)"],
  "backups.save_world": ["Save the world now", "Run save-all"],
  "backups.save_sent": ["Saving the world.", "save-all flush sent"],
  "backups.worlds": ["Worlds", "Worlds"],
  "backups.col_world": ["World", "World"],
  "backups.col_size": ["Size", "Size"],
  "backups.col_modified": ["Last changed", "Last modified"],
  "backups.col_last_backup": ["Last backup", "Last backup"],
  "backups.col_name": ["Name", "Name"],
  "backups.col_type": ["Type", "Type"],
  "backups.col_created": ["Made", "Created"],
  "backups.world_missing": ["Not there", "not present"],
  "backups.list": ["Backups", "Backups"],
  "backups.keeping": ["Old backups are cleared out automatically. Kept: the last {daily} days, {weekly} weeks and {monthly} months.", "Retention: {daily} daily, {weekly} weekly, {monthly} monthly."],
  "backups.kind_manual": ["Made by you", "manual"],
  "backups.kind_scheduled": ["Scheduled", "scheduled"],
  "backups.kind_safety": ["Safety copy", "safety"],
  "backups.verify": ["Check", "Verify"],
  "backups.checking": ["Checking…", "Verifying…"],
  "backups.verify_ok": ["This backup is complete and undamaged.", "Backup verified: archive and checksum are intact"],
  "backups.verify_failed": ["This backup is damaged: {reason}", "Verify failed: {reason}"],
  "backups.download": ["Download", "Download"],
  "backups.restore": ["Restore", "Restore"],
  "backups.delete": ["Delete", "Delete"],
  "backups.delete_title": ["Delete {name}?", "Delete {name}?"],
  "backups.delete_body": ["The backup is deleted for good. This can't be undone.", "The archive file is deleted from disk. This cannot be undone."],
  "backups.delete_confirm": ["Delete backup", "Delete backup"],
  "backups.deleted": ["Backup deleted", "Backup deleted"],
  "backups.none": ["No backups yet", "No backups yet"],
  "backups.none_hint": ["Back up now so you can undo a broken world later.", "Create one with Back up now or a schedule."],
  "backups.preparing": ["Preparing download…", "Preparing download…"],
  "backups.download_failed": ["Download failed", "Download failed"],
  "backups.restore_title": ["Restore this backup?", "Restore this backup?"],
  "backups.restore_question": ["Restore {name} from {when}?", "Restore {name} from {when}?"],
  "backups.start_after": ["Start the server when the restore finishes", "Start the server when the restore finishes"],
  "backups.restore_confirm": ["Check and restore", "Verify and restore"],
  "backups.restoring": ["Restoring. The server stops first.", "Restoring. The server will stop first."],
  "backups.restored": ["{name} is back. The world from before was kept as {safety}.", "Restored {name}. Safety copy: {safety}"],
  "backups.restore_job": ["Restoring {name}", "Restoring {name}"],
  "backups.undo": ["Undo", "Undo"],
  "backups.undo_title": ["Undo this change?", "Undo this change?"],
  "backups.undo_body": ["{title} will be undone by putting back {backup}. The server stops first, and a new safety copy is made, so this can be undone too.", "{title} will be undone by restoring {backup}. The server stops first, and a new safety copy is taken, so this can be undone too."],
  "backups.undoing": ["Undoing. The server stops first.", "Undoing. The server will stop first."],
  "backups.undone": ["Undone. {name} is back.", "Undone: {name} is back."],

  "players.online": ["Online now ({count} of {max})", "Online now ({count}/{max})"],
  "players.col_player": ["Player", "Player"],
  "players.col_uuid": ["UUID", "UUID"],
  "players.col_session": ["Playing for", "This session"],
  "players.col_first": ["First seen", "First seen"],
  "players.col_last": ["Last seen", "Last seen"],
  "players.col_sessions": ["Times joined", "Sessions"],
  "players.col_total": ["Total time played", "Total playtime"],
  "players.nobody": ["Nobody is online", "Nobody is online"],
  "players.everyone": ["Everyone seen on this server", "Everyone seen on this server"],
  "players.none": ["No players recorded yet", "No players recorded yet"],
  "players.none_hint": ["Players show up here after they join.", "Populated from join/leave log lines."],
  "players.no_ip": ["Player IP addresses are never recorded.", "Player IP addresses are deliberately not recorded."],

  "schedules.add": ["Add a schedule", "Add a schedule"],
  "schedules.name": ["Name", "Name"],
  "schedules.name_placeholder": ["Nightly backup", "Nightly backup"],
  "schedules.task": ["What to do", "Task"],
  "schedules.repeat": ["Repeat", "Repeat"],
  "schedules.when": ["When", "When"],
  "schedules.kind_daily": ["Every day", "daily"],
  "schedules.kind_weekly": ["Every week", "weekly"],
  "schedules.kind_interval": ["Every few hours", "interval"],
  "schedules.when_placeholder": ["23:00 / sun 04:00 / 6h", "23:00 / sun 04:00 / 6h"],
  "schedules.when_hint": ["For every day, a time like 23:00. For every week, a day and time like sun 04:00. For every few hours, a gap like 6h.", "daily: HH:MM. weekly: ddd HH:MM. interval: Nh or Nm."],
  "schedules.create": ["Create schedule", "Create schedule"],
  "schedules.created": ["Schedule created", "Schedule created"],
  "schedules.list": ["Schedules", "Schedules"],
  "schedules.col_name": ["Name", "Name"],
  "schedules.col_task": ["What it does", "Task"],
  "schedules.col_when": ["When", "When"],
  "schedules.col_next": ["Next time", "Next run"],
  "schedules.col_result": ["Last time", "Last result"],
  "schedules.every_daily": ["Every day at {expr}", "daily {expr}"],
  "schedules.every_weekly": ["Every week, {expr}", "weekly {expr}"],
  "schedules.every_interval": ["Every {expr}", "interval {expr}"],
  "schedules.off": ["Turned off", "disabled"],
  "schedules.turn_off": ["Turn off", "Disable"],
  "schedules.turn_on": ["Turn on", "Enable"],
  "schedules.run_now": ["Run now", "Run now"],
  "schedules.delete": ["Delete", "Delete"],
  "schedules.delete_title": ["Delete the schedule {name}?", "Delete the schedule {name}?"],
  "schedules.delete_body": ["It won't run again. Backups it made are kept.", "The schedule is removed. Its past results and backups are kept."],
  "schedules.deleted": ["Schedule deleted", "Schedule deleted"],
  "schedules.none": ["No schedules", "No schedules"],
  "schedules.none_hint": ["Add one above to back up or restart the server on its own.", "Nothing is scheduled."],

  "events.title": ["What happened recently", "Recent events"],
  "events.col_when": ["When", "When"],
  "events.col_type": ["Type", "Type"],
  "events.col_message": ["What happened", "Message"],
  "events.level_error": ["Problem", "error"],
  "events.level_warn": ["Warning", "warn"],
  "events.none": ["Nothing has happened yet", "No events recorded"],

  "crashes.title": ["Crash history", "Crash history"],
  "crashes.none": ["No crashes. Good.", "No crashes recorded."],
  "crashes.col_when": ["When", "When"],
  "crashes.col_code": ["Exit code", "Exit code"],
  "crashes.col_cause": ["Likely cause", "Likely cause"],
  "crashes.col_confidence": ["How sure", "Confidence"],
  "crashes.details": ["Details", "Details"],
  "crashes.conf_confirmed": ["Certain", "confirmed"],
  "crashes.conf_likely": ["Likely", "likely"],
  "crashes.conf_possible": ["Possible", "possible"],
  "crashes.conf_unknown": ["Not sure", "unknown"],
  "crashes.cause_unknown": ["Not known", "Unknown"],
  "crashes.dialog_title": ["Crash on {when}", "Crash on {when}"],
  "crashes.suspect_mods": ["Mods named in the log: ", "Installed mods mentioned in the log: "],
  "crashes.suspect_hint": [" (being named is not proof a mod caused it)", " - appearing in a stack trace is not evidence of causing the crash"],
  "crashes.evidence": ["Lines from the log", "Evidence"],
  "crashes.context": ["More about the crash", "Context"],
  "crashes.f_code": ["Exit code", "Exit code"],
  "crashes.f_minecraft": ["Minecraft", "Minecraft"],
  "crashes.f_loader": ["Fabric loader", "Fabric loader"],
  "crashes.f_java": ["Java", "Java"],
  "crashes.f_players": ["Players online", "Players online"],
  "crashes.f_report": ["Crash report", "Crash report"],
  "crashes.f_log": ["Saved log", "Saved log"],
  "crashes.no_players": ["Nobody", "none"],
  "crashes.no_report": ["Minecraft didn't write one", "none written by Minecraft"],
  "crashes.rule_match": ["This is a best guess from the log, not a certainty. Check the lines above before acting.", "This is a rule match on the log text, not a certainty. Check the evidence before acting."],

  "security.agent": ["This app", "Agent"],
  "security.connected": ["Connected", "Connected"],
  "security.agent_note": ["This page is talking to it", "this dashboard is talking to it"],
  "security.https": ["Secure connection", "HTTPS"],
  "security.https_off": ["Off", "disabled"],
  "security.https_off_note": ["Only this PC can connect", "plain HTTP - loopback only"],
  "security.cert_loaded": ["On", "certificate loaded"],
  "security.issued_by": ["Issued by {issuer}", "Issued by {issuer}"],
  "security.unknown_issuer": ["an unknown issuer", "unknown issuer"],
  "security.cert_unreadable": ["The certificate couldn't be read", "the certificate could not be read"],
  "security.expiry": ["Certificate runs out", "Certificate expiry"],
  "security.expiry_unreadable": ["Couldn't be read from the certificate", "could not be read from the certificate file"],
  "security.days_left": ["days left", "days remaining"],
  "security.tailscale": ["Tailscale", "Tailscale"],
  "security.ts_connected": ["Connected", "Connected"],
  "security.ts_disconnected": ["Not connected", "Not connected"],
  "security.auth": ["Sign-in", "Authentication"],
  "security.auth_on": ["Required", "enabled"],
  "security.auth_off": ["NOT SET", "NOT SET"],
  "security.auth_note": ["You stay signed in for {hours} hours", "sessions last {hours}h"],
  "security.failed": ["Failed sign-ins", "Failed sign-ins"],
  "security.failed_note": ["in the last 24 hours", "in the last 24 hours"],
  "security.covers": ["Certificate fits this address", "Certificate covers"],
  "security.covers_note": ["checked against {host}", "checked against {host}"],
  "security.covers_unset": ["No address is set to check against", "tls.hostname is not configured, so this cannot be checked"],
  "security.key_match": ["Key fits the certificate", "Key matches certificate"],
  "security.key_note": ["The private key never leaves the PC", "compared as public keys; the private key is never exposed"],
  "security.sessions": ["Signed in now ({count})", "Active sessions ({count})"],
  "security.col_user": ["User", "User"],
  "security.col_signed_in": ["Signed in", "Signed in"],
  "security.col_last_used": ["Last used", "Last used"],
  "security.col_from": ["From", "Source IP"],
  "security.col_device": ["Device", "Device"],
  "security.no_sessions": ["No active sessions", "No active sessions"],
  "security.rotate": ["Get a new sign-in key", "Rotate my token"],
  "security.rotated": ["You have a new sign-in key", "This session's token was rotated"],
  "security.revoke": ["Sign everyone out", "Revoke all sessions"],
  "security.revoke_title": ["Sign every session out?", "Sign every session out?"],
  "security.revoke_body": ["Everyone is signed out, you included. You'll sign in again.", "All sessions, including this one, are revoked. You will sign in again."],
  "security.audit": ["Who did what", "Audit log"],
  "security.col_when": ["When", "When"],
  "security.col_action": ["Action", "Action"],
  "security.col_target": ["Target", "Target"],
  "security.col_result": ["Result", "Result"],
  "security.audit_none": ["Nothing logged yet", "Nothing logged yet"],
  "security.result_ok": ["Done", "ok"],
  "security.bind": ["The app listens on {address}. Keep it private to your Tailscale network, and don't open it on your router.", "The agent is bound to {address}. Keep that address private to your tailnet; do not port-forward it."]
} /* end-strings-table */;

/* The display mode, set before first paint by theme.js from what this
   browser last used, then from the account's saved choice. */
export const display = {
  mode: document.documentElement.dataset.mode === "technical" ? "technical" : "simple",
};

export function technical() {
  return display.mode === "technical";
}

/* The text for key in the current mode, with {name} placeholders filled. */
export function t(key, values = null, mode = display.mode) {
  const entry = STRINGS[key];
  if (!entry) {
    // Shows up as a console error, which the browser check fails on.
    console.error(`Missing text: ${key}`);
    return key;
  }
  let text = entry[mode === "technical" ? 1 : 0];
  if (values) {
    text = text.replace(/\{(\w+)\}/g, (whole, name) =>
      (values[name] === undefined || values[name] === null ? whole : String(values[name])));
  }
  return text;
}

/* "1 player" / "3 players": key.one and key.other entries. */
export function tn(key, count, values = {}) {
  return t(`${key}.${count === 1 ? "one" : "other"}`, { count, ...values });
}
