"""Putting a server's software in place, and changing its version or type.

This is the second of the two documented exceptions to house rule 2 (the
dashboard never runs programs on the PC): the downloaded Forge or NeoForge
installer is run once with ``--installServer`` so it can write out the
libraries and the argument file the server is launched from. See
docs/security.md. The rules kept here:

  * every file name is generated by this app, never taken from a request or
    from a source's answer
  * everything is written inside that server's own folder
  * the type and version are checked against the list the official source
    returned before anything is downloaded
  * the installer is run as an argument list, never through a shell, with
    its working directory fixed to the server folder and its output
    captured into the install log
  * the result only takes effect through the server's normal launch

Version and type changes run through the safe-change routine
(agent/safechange.py) and the job tracker, so the server is stopped, a
verified backup is taken first, and the previous software is kept for a
one-click roll back.
"""

from __future__ import annotations

import asyncio
import logging
import os
import shutil
import time
from pathlib import Path
from typing import TYPE_CHECKING, Any

from .. import downloads, servertypes
from ..downloads import DownloadError
from ..safechange import SafeChange, run_safe_change
from ..security.paths import is_inside
from . import ServerType
from .versions import Plan, VersionError, list_versions, make_plan

if TYPE_CHECKING:
    from ..core import ServerContext
    from ..jobs import JobHandle

log = logging.getLogger("msc.servertypes.install")

INSTALL_LOG = "install-log"
# Where the previous server software is kept so a change can be rolled back.
PREVIOUS = "previous-server-software"
INSTALLER_TIMEOUT = 20 * 60  # a Forge install downloads libraries; give it time
# Files and folders every type keeps, whatever the type: the world, the
# player data and the settings are never part of "the server software".
NEVER_MOVED = frozenset(
    {
        "world",
        "world_nether",
        "world_the_end",
        "mods",
        "plugins",
        "config",
        "defaultconfigs",
        "server.properties",
        "eula.txt",
        "ops.json",
        "whitelist.json",
        "banned-players.json",
        "banned-ips.json",
        "usercache.json",
        "logs",
        "crash-reports",
        "backups",
        "mcsc-data",
    }
)


class InstallError(RuntimeError):
    """Something about putting the server software in place failed. The
    message is written for the person reading it."""


def _server_dir(ctx: ServerContext) -> Path:
    if not ctx.config.server_dir_configured:
        raise InstallError("This server's folder isn't set, so nothing was changed.")
    directory = ctx.config.server_dir
    if not directory.is_dir():
        raise InstallError(f"This server's folder is missing: {directory}")
    return directory


# ----------------------------------------------------------------------
# the Forge / NeoForge / Quilt installer
# ----------------------------------------------------------------------
def _log_path(ctx: ServerContext) -> Path:
    folder = ctx.config.data_dir / INSTALL_LOG
    folder.mkdir(parents=True, exist_ok=True)
    return folder / f"{time.strftime('%Y%m%d-%H%M%S')}-install.log"


def installer_command(java: str, installer: str, plan: Plan) -> list[str]:
    """The installer's argument list. Each type's arguments come from its
    capabilities; the only values filled in are the Minecraft and loader
    versions, which make_plan already matched against the official list."""
    from .versions import check_version

    server_type = servertypes.get(plan.type_id)
    values = {
        "minecraft": check_version(plan.minecraft, "Minecraft version"),
        "loader": check_version(plan.loader or "", f"{server_type.name} version"),
    }
    args = []
    for arg in server_type.installer_args or ("--installServer",):
        for key, value in values.items():
            arg = arg.replace("{" + key + "}", value)
        args.append(arg)
    return [java, "-jar", installer, *args]


async def run_installer(
    ctx: ServerContext,
    plan: Plan,
    java: str,
    directory: Path,
    job: JobHandle | None = None,
) -> Path:
    """Run a downloaded installer once, as an argument list, in the server
    folder. Returns the path of its captured log."""
    installer = plan.installer or ""
    path = directory / installer
    if not installer or not is_inside(directory, path.resolve()) or not path.is_file():
        raise InstallError("The setup file is missing, so nothing was installed.")
    command = installer_command(java, installer, plan)
    log_file = _log_path(ctx)
    if job:
        job.step("Setting the server up (this can take a few minutes)")
    log.info("running installer %s in %s", installer, directory)
    try:
        process = await asyncio.create_subprocess_exec(
            *command,
            cwd=str(directory),
            stdin=asyncio.subprocess.DEVNULL,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
        )
    except (OSError, ValueError) as exc:
        raise InstallError(f"The setup program couldn't be started: {exc}") from exc
    try:
        output, _ = await asyncio.wait_for(process.communicate(), timeout=INSTALLER_TIMEOUT)
    except TimeoutError:
        process.kill()
        await process.wait()
        raise InstallError(
            "Setting the server up took too long and was stopped. Nothing was changed."
        ) from None
    text = (output or b"").decode("utf-8", errors="replace")
    log_file.write_text(f"$ {' '.join(command)}\n(in {directory})\n\n{text}\n", encoding="utf-8")
    if process.returncode != 0:
        tail = "\n".join(text.strip().splitlines()[-6:])
        raise InstallError(f"Setting the server up failed. The full log is at {log_file}.\n{tail}")
    return log_file


def find_args_file(directory: Path, type_id: str) -> str | None:
    """The argument file a Forge or NeoForge install wrote, relative to the
    server folder (libraries/net/.../win_args.txt). None when there is none."""
    libraries = directory / "libraries"
    if not libraries.is_dir():
        return None
    # The installer writes both: win_args.txt separates paths with ";" and
    # unix_args.txt with ":". The wrong one leaves Java unable to find the
    # server's libraries, so only the one for this system is used.
    wanted = "win_args.txt" if os.name == "nt" else "unix_args.txt"
    candidates = sorted(libraries.rglob(wanted))
    preferred = [p for p in candidates if type_id in str(p).lower()] or candidates
    for path in preferred:
        try:
            relative = path.relative_to(directory)
        except ValueError:  # pragma: no cover - rglob stays inside
            continue
        return relative.as_posix()
    return None


# ----------------------------------------------------------------------
# installing one plan into a folder
# ----------------------------------------------------------------------
async def install_plan(
    ctx: ServerContext,
    plan: Plan,
    directory: Path,
    job: JobHandle | None = None,
) -> dict[str, Any]:
    """Download and set up one version. Returns what to record: the jar or
    argument file to launch, what was downloaded and whether it was checked."""
    server_type = servertypes.get(plan.type_id)
    if server_type.launch == "exe":
        from . import bedrock

        try:
            return await bedrock.install(ctx, plan, directory, job=job)
        except (bedrock.BedrockError, DownloadError) as exc:
            raise InstallError(str(exc)) from exc
    files = []
    try:
        for item in plan.downloads:
            fetched = await downloads.download(
                item.spec, directory, job=job, label=f"Downloading {server_type.name}"
            )
            files.append({**fetched.to_dict(), "role": item.role})
    except DownloadError as exc:
        for entry in files:  # a failed download leaves nothing behind
            (directory / entry["file"]).unlink(missing_ok=True)
        raise InstallError(str(exc)) from exc

    install_log = None
    jar = plan.jar
    args_file = ""
    if plan.installer:
        install_log = await run_installer(ctx, plan, ctx.config.server.java, directory, job=job)
        (directory / plan.installer).unlink(missing_ok=True)
        if server_type.launch == "args_file":
            found = find_args_file(directory, server_type.id)
            if not found:
                raise InstallError(
                    f"{server_type.name} was set up but didn't leave a start file, so this "
                    "version can't be launched. The install log has the details."
                )
            args_file = found
            jar = ""
        elif jar and not (directory / jar).is_file():
            raise InstallError(
                f"{server_type.name} was set up but {jar} isn't there, so this version "
                "can't be launched."
            )
    elif jar and not (directory / jar).is_file():
        raise InstallError(f"The download finished but {jar} isn't there.")

    verified = all(entry["verified"] for entry in files)
    return {
        "type": plan.type_id,
        "minecraft_version": plan.minecraft,
        "loader_version": plan.loader,
        "jar": jar,
        "args_file": args_file,
        "files": files,
        "verified": verified,
        "unverified_note": None
        if verified
        else (
            f"{plan.source} publishes no checksum for this download, so it couldn't be "
            "checked against one. It was downloaded over a secure connection from the "
            "official site."
        ),
        "install_log": str(install_log) if install_log else None,
        "source": plan.source,
    }


# ----------------------------------------------------------------------
# moving the old software aside, and back
# ----------------------------------------------------------------------
def software_entries(directory: Path, server_type: ServerType) -> list[Path]:
    """What in this folder is the server software, and so is replaced when
    the version or type changes. The world, mods and settings are not."""
    found = []
    for name in server_type.software_paths:
        if name in NEVER_MOVED:
            continue
        path = directory / name
        if path.exists() and not path.is_symlink():
            found.append(path)
    return found


def move_software_aside(ctx: ServerContext, server_type: ServerType, label: str) -> dict[str, Any]:
    """Move the current server software into the data folder, so the change
    can be rolled back. The world and settings are not touched."""
    directory = _server_dir(ctx)
    keep = ctx.config.data_dir / PREVIOUS / f"{time.strftime('%Y%m%d-%H%M%S')}-{label}"
    keep.mkdir(parents=True, exist_ok=True)
    moved = []
    for path in software_entries(directory, server_type):
        shutil.move(str(path), str(keep / path.name))
        moved.append(path.name)
    return {
        "folder": str(keep),
        "moved": moved,
        "type": server_type.id,
        "jar": ctx.config.server.jar,
        "args_file": ctx.config.server.args_file,
    }


def put_software_back(ctx: ServerContext, kept: dict[str, Any]) -> list[str]:
    """Put software moved aside by ``move_software_aside`` back."""
    directory = _server_dir(ctx)
    folder = Path(kept["folder"])
    if not is_inside(ctx.config.data_dir, folder.resolve()):
        raise InstallError("That saved copy isn't in this app's own folder, so it wasn't used.")
    restored = []
    for name in kept.get("moved", []):
        source = folder / name
        if not source.exists():
            continue
        target = directory / name
        # Bedrock's built-in packs are kept as behavior_packs/<pack>.
        if not is_inside(directory, target.resolve()):
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        if target.exists():
            shutil.rmtree(target) if target.is_dir() else target.unlink()
        shutil.move(str(source), str(target))
        restored.append(name)
    return restored


def move_wrong_loader_content_aside(ctx: ServerContext, target: ServerType) -> dict[str, Any]:
    """Move mods or plugins that the new type cannot load into the trash
    folder (kept, never deleted). Returns what moved and what stayed."""
    from ..mods.jarinfo import read_mod_jar

    current = ctx.config.server_type
    source_folder = ctx.config.mods_dir
    moved, kept = [], []
    if not source_folder.is_dir() or current.content_folder == target.content_folder:
        if not source_folder.is_dir():
            return {"moved": [], "kept": [], "folder": None}
    trash = (
        ctx.config.mod_trash_dir / f"{time.strftime('%Y%m%d-%H%M%S')}-{current.id}-to-{target.id}"
    )
    for entry in sorted(source_folder.iterdir()):
        if not entry.is_file() or entry.is_symlink():
            continue
        if not entry.name.endswith(".jar") and ".jar" not in entry.name:
            continue
        info = read_mod_jar(entry, compute_hash=False)
        loaders = info.loaders or [info.loader]
        if any(loader in target.accepts for loader in loaders):
            kept.append(entry.name)
            continue
        trash.mkdir(parents=True, exist_ok=True)
        shutil.move(str(entry), str(trash / entry.name))
        moved.append(entry.name)
    return {"moved": moved, "kept": kept, "folder": str(trash) if moved else None}


# ----------------------------------------------------------------------
# the preflight
# ----------------------------------------------------------------------
async def preflight(
    ctx: ServerContext,
    type_id: str,
    minecraft: str,
    loader: str | None = None,
) -> dict[str, Any]:
    """What will happen, in plain words, before anything is changed."""
    from ..minecraft.java import check_compatibility, required_java

    current = ctx.config.server_type
    target = servertypes.get(type_id)
    refuse_other_edition(current, target)
    versions = await list_versions(target.id)
    entry = next((v for v in versions if v.minecraft == minecraft), None)
    if entry is None:
        raise VersionError(f"{target.name} doesn't offer Minecraft {minecraft}.")
    if loader and entry.loaders and loader not in entry.loaders:
        raise VersionError(f"{target.name} has no version {loader} for Minecraft {minecraft}.")

    running_version = ctx.server.mc_version
    direction = "same"
    if running_version:
        from ..minecraft.java import parse_minecraft

        now, then = parse_minecraft(running_version), parse_minecraft(minecraft)
        if now and then:
            direction = "newer" if then > now else "older" if then < now else "same"

    if not target.needs_java:
        java: dict[str, Any] = {"verdict": "not_needed", "detail": None}
    else:
        if ctx.server.java_info is None:
            await asyncio.to_thread(ctx.server.detect_java)
        java_info = ctx.server.java_info
        java = (
            check_compatibility(java_info, minecraft)
            if java_info is not None
            else {"verdict": "unknown", "detail": "Java couldn't be checked on this PC."}
        )
    content = []
    if current.has_content:
        for mod in ctx.mods.scan():
            loaders = mod.loaders or [mod.loader]
            fits = any(name in target.accepts for name in loaders)
            declared = mod.minecraft_range or ""
            content.append(
                {
                    "name": mod.name,
                    "filename": mod.filename,
                    "enabled": mod.enabled,
                    "loaders": loaders,
                    # True, False or None: None means nothing in the file
                    # says, so it is Unknown rather than a guess.
                    "fits_type": fits,
                    "declares_target": _declares(mod, minecraft) if declared else None,
                    "declared_range": declared or None,
                }
            )
    moved_aside = [c for c in content if not c["fits_type"]]
    return {
        "current": {
            "type": current.id,
            "type_name": current.name,
            # Only what the console actually reported, or null for Unknown.
            "minecraft_version": running_version,
            "loader_version": ctx.server.loader_version,
            "observed": bool(running_version),
        },
        "target": {
            "type": target.id,
            "type_name": target.name,
            "minecraft_version": minecraft,
            "loader_version": loader or (entry.loaders[0] if entry.loaders else None),
            "stable": entry.stable,
        },
        "type_change": target.id != current.id,
        "gentle_type_change": {current.id, target.id} <= {"vanilla", "paper", "purpur"},
        "direction": direction,
        "downgrade_warning": direction == "older",
        "java": java,
        "java_required": required_java(minecraft) if target.needs_java else None,
        # Bedrock: Mojang offers only the newest version; older ones only
        # where a copy was kept.
        "latest_only": target.latest_only,
        "kept": bool(entry.kept),
        "content_kind": current.content,
        "target_content_kind": target.content,
        "content": content,
        "moved_aside": [c["filename"] for c in moved_aside],
        "unknown_support": [c["filename"] for c in content if c["declares_target"] is None],
        # Add-ons that stay but say they don't support the target version:
        # the ones most likely to stop the server starting.
        "not_supporting": [
            c["filename"] for c in content if c["fits_type"] and c["declares_target"] is False
        ],
        "backup_first": True,
        "crossplay": ctx.config.server.crossplay,
        "crossplay_available": target.crossplay,
    }


def refuse_other_edition(current: ServerType, target: ServerType) -> None:
    """Java and Bedrock keep their worlds in different formats, so a server
    never changes between them."""
    if not current.can_change_to(target):
        raise InstallError(
            f"A {current.name} server can't become a {target.name} server: their worlds are "
            "stored differently. Create a new server instead (the + tab)."
        )


def _declares(mod, minecraft: str) -> bool | None:
    from ..mods.jarinfo import range_satisfies

    syntax = next((d.syntax for d in mod.dependencies if d.mod_id == "minecraft"), "fabric")
    return range_satisfies(minecraft, mod.minecraft_range, syntax)


# ----------------------------------------------------------------------
# the change itself
# ----------------------------------------------------------------------
async def change_version(
    ctx: ServerContext,
    type_id: str,
    minecraft: str,
    loader: str | None = None,
    user: str = "system",
    start_after: bool = False,
) -> dict[str, Any]:
    """Change this server's version, or its type, through the safe-change
    routine and the job tracker. Returns the job's result."""
    from ..events import Event

    target = servertypes.get(type_id)
    current = ctx.config.server_type
    refuse_other_edition(current, target)
    if target.download_terms:
        from . import bedrock

        try:
            bedrock.require_terms(ctx.core.db)
        except bedrock.BedrockError as exc:
            raise InstallError(str(exc)) from exc
    plan = await make_plan(target.id, minecraft, loader)
    directory = _server_dir(ctx)
    type_change = target.id != current.id
    # What the console last reported, kept before the change clears it.
    before = ctx.server.mc_version
    previous_loader = ctx.server.loader_version
    crossplay_was_on = bool(ctx.config.server.crossplay)
    title = (
        f"Changing {ctx.name} to {target.name} {minecraft}"
        if type_change
        else f"Changing {ctx.name} to Minecraft {minecraft}"
    )

    async def apply_exe(job: JobHandle | None) -> dict[str, Any]:
        """Bedrock: only Mojang's files are replaced, moved aside with their
        folder layout once the new download is here."""
        from . import bedrock

        label = f"{current.id}-{ctx.server.mc_version or 'unknown'}"
        keep = ctx.config.data_dir / PREVIOUS / f"{time.strftime('%Y%m%d-%H%M%S')}-{label}"
        old_record = bedrock.shipped_record(ctx)
        try:
            result = await bedrock.install(ctx, plan, directory, job=job, keep=keep)
        except (bedrock.BedrockError, DownloadError) as exc:
            raise InstallError(str(exc)) from exc
        kept = {
            "folder": str(keep),
            "moved": result.pop("moved_aside"),
            "type": current.id,
            "jar": ctx.config.server.jar,
            "args_file": ctx.config.server.args_file,
            "shipped": old_record,
        }
        return {
            **result,
            "previous": kept,
            "content_moved_aside": {"moved": [], "kept": [], "folder": None},
        }

    async def apply(job: JobHandle | None) -> dict[str, Any]:
        if target.launch == "exe":
            return await apply_exe(job)
        kept = move_software_aside(
            ctx, current, f"{current.id}-{ctx.server.mc_version or 'unknown'}"
        )
        moved_content: dict[str, Any] = {"moved": [], "kept": [], "folder": None}
        try:
            if type_change:
                moved_content = move_wrong_loader_content_aside(ctx, target)
            result = await install_plan(ctx, plan, directory, job=job)
        except BaseException:
            # Put the old software back, so a failed change leaves the
            # server exactly as it was.
            for entry in plan.downloads:
                (directory / entry.spec.name).unlink(missing_ok=True)
            if plan.jar:
                (directory / plan.jar).unlink(missing_ok=True)
            try:
                put_software_back(ctx, kept)
            except Exception:  # pragma: no cover - reported, never hidden
                log.exception("could not put the previous server software back")
            raise
        return {**result, "previous": kept, "content_moved_aside": moved_content}

    async def check(result: dict[str, Any]) -> tuple[bool, str]:
        """The files are really there and the server can be launched."""
        if result["args_file"]:
            path = directory / result["args_file"]
            if not path.is_file():
                return False, f"{target.name}'s start file isn't there after the change"
            return True, f"{target.name}'s start file is in place ({result['args_file']})"
        jar = directory / result["jar"]
        if not jar.is_file():
            return False, f"{result['jar']} isn't there after the change"
        if jar.stat().st_size < 1024:
            return False, f"{result['jar']} is too small to be a server file"
        return True, f"{result['jar']} is in place ({jar.stat().st_size} bytes)"

    change = SafeChange(
        title=title,
        change=apply,
        check=check,
        stop_server=True,
        start_after=start_after,
        take_backup=True,
        backup_name="pre-version-change",
        backup_note=f"Automatic safety copy before: {title}",
    )

    async def run(job: JobHandle | None) -> dict[str, Any]:
        outcome = await run_safe_change(ctx.server, ctx.backups, change, job=job, user=user)
        # Only now is the new software what this server is: the config and
        # the database row follow the change, not the request.
        ctx.config.set("server.type", target.id)
        ctx.config.set("server.jar", outcome["jar"])
        ctx.config.set("server.args_file", outcome["args_file"])
        if target.content_folder and target.content_folder != current.content_folder:
            ctx.config.set("mods.directory", target.content_folder)
        # Geyser and Floodgate are built for one kind of server, so after a
        # type change the ones in place belong to the old kind (they were
        # moved aside with the other add-ons). Crossplay is switched off
        # rather than shown as on when it can't work; turning it on again
        # fetches the builds for the new kind.
        crossplay_off = type_change and crossplay_was_on
        if crossplay_off:
            ctx.config.set("server.crossplay", False)
        ctx.config.save()
        ctx.core.db.set_server_software(ctx.server_id, target.id, outcome["loader_version"])
        ctx.core.db.register_server(
            ctx.server_id, ctx.config.server.name, str(directory), target.id
        )
        # The version is "pending" until the console reports it (house rule 1).
        ctx.server.pending_version = {
            "type": target.id,
            "minecraft_version": minecraft,
            "loader_version": outcome["loader_version"],
            "since": time.time(),
        }
        ctx.server.mc_version = None
        ctx.server.loader_version = None
        ctx.db.set_setting(
            "version_change",
            {
                "at": time.time(),
                "type": target.id,
                "minecraft_version": minecraft,
                "loader_version": outcome["loader_version"],
                "previous": outcome["previous"],
                "previous_type": current.id,
                "previous_loader": previous_loader,
                "content_moved_aside": outcome["content_moved_aside"],
                "install_log": outcome["install_log"],
                "verified": outcome["verified"],
                "user": user,
            },
        )
        await ctx.bus.publish(
            Event(
                type="version_changed",
                level="success",
                message=(
                    f"{ctx.name} is set up as {target.name} {minecraft}. Its version shows as "
                    "pending until it starts and reports it."
                ),
                data={
                    "type": target.id,
                    "minecraft_version": minecraft,
                    "loader_version": outcome["loader_version"],
                    "verified": outcome["verified"],
                    "moved_aside": outcome["content_moved_aside"]["moved"],
                },
            )
        )
        return {**outcome, "crossplay_turned_off": crossplay_off}

    job, result = await ctx.core.jobs.run(
        "version_change", title, run, server_id=ctx.server_id, risky=True, user=user
    )
    ctx.core.db.audit(
        "version_change",
        user=user,
        target=ctx.server_id,
        detail=f"{current.id} {before or 'unknown'} -> {target.id} {minecraft}",
        server_id=ctx.server_id,
    )
    return {
        **result,
        "job_id": job.id,
        "pending": True,
        "pending_note": (
            "The version shows as pending until the server starts and its console reports it."
        ),
    }


async def roll_back(ctx: ServerContext, user: str = "system") -> dict[str, Any]:
    """Put the previous version's software back, from the copy the last
    change kept."""
    from ..events import Event

    record = ctx.db.get_setting("version_change")
    if not record or not record.get("previous"):
        raise InstallError("There's no previous version to go back to.")
    previous = record["previous"]
    folder = Path(previous.get("folder", ""))
    if not folder.is_dir():
        raise InstallError("The copy of the previous version is no longer there.")
    previous_type = servertypes.get(record.get("previous_type") or previous.get("type"))
    target_type = servertypes.get(record.get("type"))
    title = f"Going back to {previous_type.name} on {ctx.name}"

    async def apply(job: JobHandle | None) -> dict[str, Any]:
        if job:
            job.step("Putting the previous version back")
        directory = _server_dir(ctx)
        for entry in software_entries(directory, target_type):
            shutil.rmtree(entry) if entry.is_dir() else entry.unlink()
        if target_type.launch == "exe":
            from . import bedrock

            # What the change unpacked goes; what it replaced comes back.
            now = bedrock.shipped_record(ctx) or {}
            for relative in [*now.get("top", []), *now.get("packs", [])]:
                path = directory / relative
                if path.exists() and not path.is_symlink():
                    shutil.rmtree(path) if path.is_dir() else path.unlink()
            ctx.db.set_setting(bedrock.SHIPPED_KEY, previous.get("shipped"))
        restored = put_software_back(ctx, previous)
        moved = record.get("content_moved_aside") or {}
        put_back = []
        if moved.get("folder") and Path(moved["folder"]).is_dir():
            content_folder = (
                directory / (previous_type.content_folder or "mods")
                if previous_type.has_content
                else None
            )
            if content_folder:
                content_folder.mkdir(parents=True, exist_ok=True)
                for path in sorted(Path(moved["folder"]).iterdir()):
                    if path.is_file():
                        shutil.move(str(path), str(content_folder / path.name))
                        put_back.append(path.name)
        return {"restored": restored, "content_restored": put_back}

    async def check(result: dict[str, Any]) -> tuple[bool, str]:
        ctx.config.set("server.type", previous_type.id)
        ctx.config.set("server.jar", previous.get("jar") or previous_type.jar)
        ctx.config.set("server.args_file", previous.get("args_file") or "")
        if previous_type.content_folder:
            ctx.config.set("mods.directory", previous_type.content_folder)
        problem = ctx.server.launch_problem()
        if problem:
            return False, problem
        return True, f"{previous_type.name} is back in place"

    change = SafeChange(
        title=title,
        change=apply,
        check=check,
        stop_server=True,
        take_backup=True,
        backup_name="pre-rollback",
        backup_note=f"Automatic safety copy before: {title}",
    )

    async def run(job: JobHandle | None) -> dict[str, Any]:
        outcome = await run_safe_change(ctx.server, ctx.backups, change, job=job, user=user)
        ctx.config.save()
        ctx.core.db.set_server_software(
            ctx.server_id, previous_type.id, record.get("previous_loader")
        )
        ctx.server.pending_version = None
        ctx.server.mc_version = None
        ctx.server.loader_version = None
        ctx.db.set_setting("version_change", None)
        await ctx.bus.publish(
            Event(
                type="version_rolled_back",
                level="warn",
                message=f"{ctx.name} is back on {previous_type.name}",
                data={"type": previous_type.id, "restored": outcome["restored"]},
            )
        )
        return outcome

    job, result = await ctx.core.jobs.run(
        "version_rollback", title, run, server_id=ctx.server_id, risky=True, user=user
    )
    ctx.core.db.audit("version_rollback", user=user, target=ctx.server_id, server_id=ctx.server_id)
    return {**result, "job_id": job.id, "type": previous_type.id}
