"""Generate the keys phone alerts need.

    python -m installer.make_push_keys

Web Push asks every sender to identify itself with a key pair of its own
(RFC 8292). This makes one and prints the three lines to add to the agent's
.env file. The pair belongs to this installation: replacing it means every
phone has to turn alerts on again.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from agent.notifications.push import generate_keys

ENV_PATH = Path(__file__).resolve().parent.parent / ".env"


def main() -> int:
    print("Minecraft Server Control - phone alert keys")
    print("-" * 42)
    public, private = generate_keys()
    contact = input("An email address push services can contact you at (optional): ").strip()
    lines = [
        "",
        "# Phone alerts (Web Push). Generated by installer/make_push_keys.py.",
        f"MCSC_VAPID_PUBLIC_KEY={public}",
        f"MCSC_VAPID_PRIVATE_KEY={private}",
        f"MCSC_PUSH_SUBJECT={f'mailto:{contact}' if contact else ''}",
    ]
    block = "\n".join(lines) + "\n"

    if ENV_PATH.exists():
        text = ENV_PATH.read_text(encoding="utf-8")
        if "MCSC_VAPID_PRIVATE_KEY" in text:
            print(f"\n{ENV_PATH} already has phone alert keys, so nothing was changed.")
            print("To replace them, delete those lines and run this again. Every phone")
            print("will then have to turn alerts on once more.\n")
            print(block)
            return 0
        with ENV_PATH.open("a", encoding="utf-8") as fh:
            fh.write(block)
        print(f"\nAdded the keys to {ENV_PATH}")
    else:
        ENV_PATH.write_text(block.lstrip("\n"), encoding="utf-8")
        try:
            ENV_PATH.chmod(0o600)
        except OSError:
            pass
        print(f"\nWrote {ENV_PATH}")
    print("Restart the agent, then turn on Phone alerts in App settings and press")
    print("'Turn on for this phone' on each phone you want alerts on.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
