"""Generate the secrets the agent needs, without ever storing a password.

    python -m installer.make_secrets

It asks for a dashboard password, hashes it, mints an API token, and writes
(or prints) the lines you paste into the agent's .env file. The plain
password is never written anywhere.
"""

from __future__ import annotations

import getpass
import secrets
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from agent import appinfo
from agent.security.auth import hash_password

ENV_PATH = appinfo.default_env_path()


def main() -> int:
    print("Minecraft Server Control - secret setup")
    print("-" * 42)
    username = input("Dashboard username [admin]: ").strip() or "admin"

    while True:
        password = getpass.getpass("Dashboard password (10+ characters): ")
        if len(password) < 10:
            print("  Too short. Use at least 10 characters.")
            continue
        if password != getpass.getpass("Repeat the password: "):
            print("  The two entries do not match.")
            continue
        break

    hashed = hash_password(password)
    del password
    api_token = secrets.token_urlsafe(32)

    lines = [
        "# Generated by installer/make_secrets.py. Never commit this file.",
        f"MCSC_ADMIN_USERNAME={username}",
        f"MCSC_ADMIN_PASSWORD_HASH={hashed}",
        f"MCSC_API_TOKEN={api_token}",
        "",
        "# Paste your Discord webhook URL here to enable Discord alerts:",
        "MCSC_DISCORD_WEBHOOK=",
        "",
        "# SMTP credentials for email alerts (the host and addresses live in config.yaml):",
        "MCSC_SMTP_USERNAME=",
        "MCSC_SMTP_PASSWORD=",
    ]
    content = "\n".join(lines) + "\n"

    if ENV_PATH.exists():
        print(f"\n{ENV_PATH} already exists, so nothing was overwritten.")
        print("Replace these lines in it by hand:\n")
        print(content)
        return 0

    ENV_PATH.write_text(content, encoding="utf-8")
    try:  # tighten permissions where the platform supports it
        ENV_PATH.chmod(0o600)
    except OSError:
        pass
    print(f"\nWrote {ENV_PATH}")
    print(f"Username    : {username}")
    print(f"API token   : {api_token}")
    print("\nKeep the API token somewhere safe. It is only shown here, and it grants")
    print("the same access as signing in. Restart the agent for the change to apply.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
